### PR TITLE
PiCamera-based camera provider for Raspberry Pi

### PR DESCRIPTION
**Pull request by whitelynx**
Added a new camera provider based on [PiCamera](https://picamera.readthedocs.io/en/release-1.13/index.html), for use with CSI-based cameras on the Raspberry Pi. (not for USB cameras)

### CODE REVIEW

**Comment by tito** [comment]
Nothing to say about the PR, thanks for all!

**Comment by tito** [comment]
Can you also check the documentation part about the requirements needed for the camera on RPI ? (Numpy + picamera)

**Comment by bionoid** [comment]
Seems like numpy is only used to chop off some "bonus" pixels..? Assuming it's not a requirement of PiCamera in the first place, you could maybe avoid it with a "master" texture (at the full/rounded size), and `master_texture.get_region(0, 0, cropped_w, cropped_h)` for drawing or a Cython snippet?

Related: PR #5210 - seems like it does similar things without external dependencies

**Comment by whitelynx** [comment]
I do like the fact that #5210 doesn't require `numpy`... I'd be fine with that one replacing mine, if someone more comfortable with the C/Cython side of things could review it.

In the meantime, I'll look at using your suggestion for cutting out the `numpy` dep in this one :)

**Comment by tito** [comment]
meh :/ i didn't knew about #5210, why this was wasn't merged :(

**Pull request merged**
