### PR TITLE
Buildozer is now in Beta.

### PR DESCRIPTION
**Pull request by Julian-O**
Documentation says Buildozer is in alpha.

It is currently in beta. ([Ref](https://pypi.org/project/buildozer/))

### CODE REVIEW

**Comment by matham** [comment]
That version tag may just be wrong because it started out in beta: https://github.com/kivy/buildozer/commit/d053ef783159e6d862c101f78f420896ed2bdb37.

**Comment by Julian-O** [comment]
I understand your point.

So, now I don't know whether Buildozer or Kivy documentation is right, and where the issue should be raised. It seems to me the Buildozer's setup.py is a more authoritative source, but I don't know the project's history.

What do you suggest I do next?

**Comment by matham** [comment]
I would ask on the dev channel on discord because there are buildozer devs there would know the true state of it, whether it should be considered as alpha or beta. Personally, I'm not familiar with it enough to know either way.

**Comment by Julian-O** [comment]
Buildozer already has merged a batch updating their status to Production/Stable that should become visible in their next release. Should revisit this at that point.

**Pull request merged**
