### PR TITLE
Add project description for PyPI (convert README to rst and read)

### LINKED ISSUE #5353: Kivy does not have a project description at https://pypi.org/project/Kivy/
https://pypi.org/project/Kivy/

For the project description to appear in the listing, it seems it has to be added as the `long_description` kwarg to setup in the setup.py.

In python-for-android I just read in the README.rst and pass this as the long_description. Kivy could do something similar, although currently it has a README.md which would not display properly as pypi only supports rst.

### PR DESCRIPTION
**Pull request by KeyWeeUsr**
Converts `README` to the PyPI accepted format (RST). The RST on GitHub doesn't support `raw` directives, not does it look good in tables and you can't change style, so there would be an ugly border around the logo + text.

This is probably the happiest alternative, but if you have a prettier one, feel free to share.

image

↓

image

Closes #5353 

Edit: Hopefully it'll preserve the changes if I do renaming first, modifying later.

### CODE REVIEW

**Comment by dessant** [comment]
ref https://github.com/pypa/warehouse/issues/869

**Comment by KeyWeeUsr** [comment]
@dessant hm... Pandadoc or something?

**Comment by dessant** [comment]
@KeyWeeUsr, yes, if auto-conversion gives an acceptable output. As discussed on irc, the dependency would only be used during a pypi publish and toggled by an env var.

**Comment by tshirtman** [comment]
PyPi recently updated to new version, and we currently don't feature any project description there, would be nice to fix that in next release.

https://pypi.org/project/Kivy/

**Comment by dolang** [comment]
The new PyPI supports Markdown, however. So now you have a choice.

**Comment by KeyWeeUsr** [comment]
Closed in favor of #5762

**Pull request closed without merging**
