### PR TITLE
Update pep8.py to version 1.7.0

### PR DESCRIPTION
**Pull request by udiboy1209**
Update pep8.py to 1.7.0 while copying over [a2ea270](https://github.com/kivy/kivy/commit/a2ea270f750d90673f63dbc7b6ed63b8c5c1d7ce#diff-43b700e60750dd13b002d04cc62dd894) and [0c34d76](https://github.com/kivy/kivy/commit/0c34d760570ec19d4ce0eca1317e441603113443). 

@dessant  there are 1109 instances of E402(module level import not at top of file). Should I add it to the ignore list?

### CODE REVIEW

**Comment by dessant** [comment]
Yes, that could be ignored.

**Comment by dessant** [comment]
Just seen that the current version is 2.2.0, did you use an alternate source?
https://github.com/PyCQA/pycodestyle/releases
https://github.com/PyCQA/pycodestyle/blob/2.2.0/pycodestyle.py

**Comment by udiboy1209** [comment]
@dessant  I downloaded the source from PyPi and its 1.7.0 on PyPi so that is what I used. Want to update to 2.2.0 from github?

**Comment by dessant** [comment]
Yes, it would be preferred. They renamed the project to pycodestyle: https://pypi.python.org/pypi/pycodestyle.

**Comment by udiboy1209** [comment]
Ahh lol alright :+1:

**Pull request merged**
