### PR TITLE
Compound selection bug 

### LINKED ISSUE #4915: Compound selection nonstandard behavior
Tested with [this](https://github.com/kivy/kivy/blob/master/examples/widgets/compound_selection.py) example. Steps to reproduce:

* click first item
* Shift+click fifth item
* Ctrl+click first, second and third item
* Shift+click fourth item

Kivy:
kivy

Windows 10 file explorer:
windows

PCManFM:
pcmanfm

Nautilus:
nautilus

### PR DESCRIPTION
**Pull request by saqib1707**
@dessant This pr fixes #4915 .Well the problem was occuring because after deleting the anchor element in a range selection it was not updated causing all the deleted nodes to reappear as shown in the issue [here](https://github.com/kivy/kivy/issues/4915).So I updated the anchor element to the first next selected element.
Testing-[code](https://github.com/kivy/kivy/blob/master/examples/widgets/compound_selection.py)

### CODE REVIEW

**Comment by malverick** [comment]
Hi @saqib1707 
I found the following issues while testing the pr. :)
https://www.youtube.com/playlist?list=PLZRlOTwWkDYMQGi_FRzMeu3rs0Mo3hiFD
I have provided the steps to recreate each issue in respective video's description :).
First, I followed these steps in your code with videos named `issue 1`, `issue 2`, `issue 3`, `issue 4`.
Secondly, I followed the same steps in windows platform with videos named win 1, win 2, win 3, win 4 for respective issue videos.
The issues shown here are just the examples. Many similar issues were happening with different combinations of steps.
Although, some issues are not relevant to the original issue as @dessant 's issue only asks to fix the shift+click bug, but just mentioning here because I found them while working on my PR.

**Comment by saqib1707** [comment]
Well @malverick the 4 issues that u have mentioned are the way they are intended to be and I don't think they are issues.Regarding the issues on window , I don't have access to windows so won't be able to reproduce it right now.

**Comment by dessant** [comment]
@saqib1707, @malverick, thanks guys, we will take a look at the two prs in the next few days, please leave them as is.

**Comment by phunsukwangdu** [comment]
@dessant  since competition is over shall i also send my pr?

**Comment by dessant** [comment]
@phunsukwangdu, we have not yet reviewed the existing prs to see if one of them fixes the issue.

**Comment by phunsukwangdu** [comment]
@dessant sure i will abide by you. :) The reason i am so curious and excited about my pr is that i solved the issue by just inserting a single line in codebase.

**Comment by dessant** [comment]
The pr does not fix the test case in #4915. Closing in favor of https://github.com/kivy/kivy/pull/4916.

**Pull request closed without merging**
