### PR TITLE
fixing issue #2297 with blurred labels in scrollview

### PR DESCRIPTION
**Pull request by pyfrid**
1) changing min and mag filter of label texture to nearest in kivy.core.text
2) rounding scrollview translate coordinates to integer in kivy.uix.scrollview

### CODE REVIEW

**Comment by inclement** [comment]
I don't think the rounding to integer is desirable, as it will lead to jerky motion on lower-resolution displays. Maybe it could be an option.

**Comment by pyfrid** [comment]
Without rounding, text will be pixelized if position of scrollview has been changed.

**Comment by inclement** [comment]
That's why I suggest making it an option - both rounding and not rounding are apparently desirable modes.

**Comment by dessant** [comment]
If we go the config option way, one that also affects all pos/size props would be great, because blurring caused by subpixel rendering is a problem with all textures, not just text.

**Comment by dessant** [comment]
It is also not just a problem inside scrollview, but it can appear anywhere, commonly when `size_hint` is used.

**Comment by pyfrid** [comment]
I propose a general config option for the default filter for all textures and a boolean property for scrollview for translation rounding. Concerning common problem everywhere where size_hint is used I need examples. In my large application with a lot of layouts and fixed size widgets I have issue only with scrollview. Even in my example to the corresponding issue tab labels become blurred because they are placed to scrollview by default with horizontal scrolling. 

I will work on that during weekends.

**Comment by tito** [comment]
Changing the mag filter or using int will mislead the resolution of this issue. I mean, as an user, if i activate this option, i expect that it will be not blurry and works. But it wont, if the widget tree is not pixel aligned.

I think we can make the distinction between 2 phases:
- when something animate: we want smooth animation, int is not desirable, as well as mag filter.
- when it's static: we want pixel-perfect rendering, no blur.

This could be resolved by a total another approach, more general:
1. ensure all the layout are computing pixel perfect layout, no half pixel: ie, use int() when it should be, as long as the width or height is an integer as well (we can't have pixel perfect calculation if the width/height are not integer). size_hint could compute integer width/height as well.
2. ensure any scrollview will end the scrolling to a pixel, not a portion of it. So when moving / animating, stay as today, but when we reach the end of the movement (delta too low to say there is a movement), then move to the nearest pixel in the direction of the movement.

That should cover all the standard case. The one that wont work will be the one when user use its own matrix and do it's own translation.

**Comment by tito** [comment]
Changing the label rendering and using integer will break all the current animation or usage of subpixel application, so it's not acceptable :)

But thanks for your first contribution!

**Comment by pyfrid** [comment]
Thank you Mathieu, for clear explanation. I will try your proposal.

**Pull request closed without merging**
