### PR TITLE
fix KIVY_EVENTLOOP doc

### PR DESCRIPTION
**Pull request by gottadiveintopython**
#6484

### CODE REVIEW

**Comment by matham** [comment]
Sync is not an accepted backend for asynio so there's no reason to support it. Especially to mean asyncio.

We did support it before, but then unrealized there was no reason for it so I removed it. Why do you want to accept sync as a backend name to mean asyncio?

**Comment by gottadiveintopython** [comment]
If the user doesn't set `KIVY_EVENTLOOP`

```python
from kivy.app import runTouchApp
from kivy.uix.widget import Widget

runTouchApp(Widget())
```

the following part

https://github.com/kivy/kivy/blob/3d87584b963a79465ed52e09f4de17395c6aae60/kivy/clock.py#L1075-L1077

will be evaluated to

```python
    Clock = register_context(
        'Clock', _classes[_clk],
        async_lib='asyncio')
```

which doesn't cause the error. But if the user set  `KIVY_EVENTLOOP` to `sync`

```python
import os
os.environ['KIVY_EVENTLOOP'] = 'sync'
from kivy.app import runTouchApp
from kivy.uix.widget import Widget

runTouchApp(Widget())
```

that part will be evaluated to

```python
    Clock = register_context(
        'Clock', _classes[_clk],
        async_lib='sync')
```

which causes the error. This PR makes the latter behave the same as the former.

**Comment by gottadiveintopython** [comment]
The error comes from

https://github.com/kivy/kivy/blob/3d87584b963a79465ed52e09f4de17395c6aae60/kivy/clock.py#L532-L559

For me, it looks like we have to set `async_lib` to `asyncio` even though the event loop is run in 'sync' manner.

**Comment by gottadiveintopython** [comment]
@matham 
> Sync is not an accepted backend for asynio so there's no reason to support it. Especially to mean asyncio.

This PR is not trying to do something like that.

**Comment by matham** [comment]
I don't understand why you're setting `KIVY_EVENTLOOP` to `sync`? `KIVY_EVENTLOOP` is supposed to be used to set the default async library to use when you're doing async. If you're not doing async, there's no reason to set it, especially not to `sync`.

Perhaps the variable needs to be renamed to e.g. `KIVY_ASYNC_LIB` and that is the confusion?

**Comment by gottadiveintopython** [comment]
> KIVY_EVENTLOOP is supposed to be used to set the default async library ...

The reason why I set `KIVY_EVENTLOOP` to `'sync'` is the [doc](https://github.com/kivy/kivy/blob/master/doc/sources/guide/environment.rst#event-loop). Shoud I fix the doc?

> Perhaps the variable needs to be renamed ...

Either is fine. For me both sound natural.

**Comment by matham** [comment]
Yeah, that doc needs to be fixed. I do think `KIVY_ASYNC_LIB` as a little better as the name is clearer in relation to what the variable does, but I'm not sure if it's a good idea to change it at this point.

**Comment by gottadiveintopython** [comment]
Done. But since I'm not fluent in English, I probably shouldn't do this kind of stuffs.

> but I'm not sure if it's a good idea to change it at this point.

I'm ok with changing it.

**Comment by gottadiveintopython** [comment]
thanks @matham

**Pull request merged**
