### PR TITLE
Fix: Hang in clipboard_xsel.py

### PR DESCRIPTION
**Pull request by SanAndreyas**
Hangs when using clipboard because it waits for input from stdin.

Maintainer merge checklist
* [ ] Title is descriptive/clear for inclusion in release notes.
* [ ] Applied a `Component: xxx` label.
* [ ] Applied the `api-deprecation` or `api-break` label.
* [ ] Applied the `release-highlight` label to be highlighted in release notes.
* [ ] Added to the milestone version it was merged into.
* [ ] **Unittests** are included in PR.
* [ ] Properly documented, including `versionadded`, `versionchanged` as needed.

### CODE REVIEW

**Comment by misl6** [comment]
Hi @SanAndreyas !

The issue is not reproducible on my side, and we do not have reports for that.
Can you please add some more info?

**Comment by SanAndreyas** [comment]
OS: Debian [Bullseye]
I used anaconda3 to install python 3.10
kivy is latest

 File "MainMenu.py", line 759, in show_info
     self.infopopup = InfoPopup()
   File "MainMenu.py", line 245, in __init__
     super(InfoPopup, self).__init__()
   File "/anaconda3/envs/MB/lib/python3.10/site-packages/kivy/uix/modalview.py", line 195, in __init__
     super(ModalView, self).__init__(**kwargs)
   File "/anaconda3/envs/MB/lib/python3.10/site-packages/kivy/uix/anchorlayout.py", line 68, in __init__
     super(AnchorLayout, self).__init__(**kwargs)
   File "/anaconda3/envs/MB/lib/python3.10/site-packages/kivy/uix/layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "/anaconda3/envs/MB/lib/python3.10/site-packages/kivy/uix/widget.py", line 366, in __init__
     self.apply_class_lang_rules(
   File "/anaconda3/envs/MB/lib/python3.10/site-packages/kivy/uix/widget.py", line 470, in apply_class_lang_rules
     Builder.apply(
   File "/anaconda3/envs/MB/lib/python3.10/site-packages/kivy/lang/builder.py", line 540, in apply
     self._apply_rule(
   File "/anaconda3/envs/MB/lib/python3.10/site-packages/kivy/lang/builder.py", line 662, in _apply_rule
     self._apply_rule(
   File "/anaconda3/envs/MB/lib/python3.10/site-packages/kivy/lang/builder.py", line 658, in _apply_rule
     child = cls(__no_builder=True)
   File "/anaconda3/envs/MB/lib/python3.10/site-packages/kivy/uix/textinput.py", line 612, in __init__
     self._ensure_clipboard()
   File "/anaconda3/envs/MB/lib/python3.10/site-packages/kivy/uix/textinput.py", line 2008, in _ensure_clipboard
     from kivy.core.clipboard import Clipboard, CutBuffer
   File "/anaconda3/envs/MB/lib/python3.10/site-packages/kivy/core/clipboard/__init__.py", line 141, in <module>
     Clipboard = core_select_lib('clipboard', _clipboards, True)
   File "/anaconda3/envs/MB/lib/python3.10/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
     mod = importlib.__import__(name='{2}.{0}.{1}'.format(
   File "/anaconda3/envs/MB/lib/python3.10/site-packages/kivy/core/clipboard/clipboard_xsel.py", line 17, in <module>
     p.communicate()
   File "/anaconda3/envs/MB/lib/python3.10/subprocess.py", line 1141, in communicate
     stdout = self.stdout.read()

**Comment by misl6** [comment]
May have been fixed via #8682 ?

**Comment by SanAndreyas** [comment]
> May have been fixed via #8682 ?

yes. it that solution also fixes it.

**Comment by misl6** [comment]
Ok, closing in favor of #8682.

Thank you!

**Pull request closed without merging**
