### PR TITLE
core-providers (audio): removes deprecated `status` property

### PR DESCRIPTION
**Pull request by Zerus97**
#8177 

Maintainer merge checklist
* [x] Title is descriptive/clear for inclusion in release notes.
* [x] Applied a `Component: xxx` label.
* [ ] Applied the `api-deprecation` or `api-break` label.
* [x] Applied the `release-highlight` label to be highlighted in release notes.
* [x] Added to the milestone version it was merged into.
* [ ] **Unittests** are included in PR.
* [ ] Properly documented, including `versionadded`, `versionchanged` as needed.

### CODE REVIEW

**Comment by misl6** [comment]
Hi @Zerus97 !

We're using this deprecated property in one of our examples 😅 

Can you also change the following in order to not use the deprecated property, so we are sure to not break examples / demos?

https://github.com/kivy/kivy/blob/ee040926edd6e68d13e8799484c25d6e2911397b/examples/audio/main.py#L36

**Comment by Zerus97** [comment]
Hi @misl6 , how are you doing?

Ive just commited the change you asked for using the state property as indicated.

**Comment by misl6** [comment]
Hi @Zerus97 !

We now have a conflict, can you resolve it? (make sure to rebase on upstream/master)

**Review by misl6 — APPROVED** [review]
LGTM. Thank you!

**Pull request merged**
