### PR TITLE
Picibucor

### PR DESCRIPTION
**Pull request by picibucor**
A container-example was added.

### CODE REVIEW

**Comment by tito** [comment]
Hi @picibucor! Thanks for this contribution :)

I suggest you to make it pep8 compliant (just `pip install pep8 pyflakes`) and use it on your main file: `pep8 main.py`. Same with pyflakes.

This will highlight some issues in the current submission, such as the non-used ActionBar import etc.

Also, could you add a description at the top explaining what is the intent of this example? (i know that something we miss most of the time, but it's time to change ^^)

Thanks you!

**Comment by dessant** [comment]
@picibucor running `make hook` will also ensure that there are no style issues in commits.

**Comment by picibucor** [comment]
As I written this is my first PR, so thx for helping.
I've tried to beautify my code before commiting...

@tito: 
I've tried both: Error by pyflakes: "TypeError: unorderable types: str() NoneType"
- pip install pyflakes
- pip3 install pyflakes
Using: Win7 ; Python3.x
How to install it?

@dessant:
Could you help me? I'm pretty newbee. How/Where to run "make hook"?

**Comment by ohaz** [comment]
I have those issues too. Installing for python2 worked. Somehow installing it in python3 throws that error

**Comment by dessant** [comment]
@picibucor when you are at your local repository, issue `make hook` in your terminal. This will install our git hook and warn you about any stylistic issues when you commit something. If it catches a problem, the commit is aborted and you can fix the mentioned error, then try committing again.

**Comment by picibucor** [comment]
@dessant :
I do not have terminal, I have commander.

I've typed the following command:
-> cd C:\Users\...\GitHub\kivy\examples\container
-> make hook
Message (translated): "by typing the command "make" you could make a typo, or the command is false"

**Comment by dessant** [comment]
@picibucor do this:
-> cd C:\Users...\GitHub\kivy
-> make hook

It will tell you that the hook was installed and you are done.

**Comment by picibucor** [comment]
still the same message:
image

**Comment by akshayaurora** [comment]
@picibucor :+1:

**Comment by picibucor** [comment]
still: "make hook" and pyflakes does not work...

**Pull request merged**
