### PR TITLE
gestures/gesture_board.py -- docstring and screenshot

### PR DESCRIPTION
**Pull request by merriam**

### CODE REVIEW

**Comment by dessant** [comment]
I'm not sure what is happening with those 3 consecutive spaces, we discussed this so much, you even wrote a style hook for it. The screenshot seems kinda off around the borders.

But other than that, +1 for it, if you fix the mentioned problems, this should be mergeable.

**Comment by merriam** [comment]
I run it manually; git gets enough confusion issues as it was.  Fixed it.  Generally, don't worry about the spaces.  A week ago there were hundreds of spacing issues in dozens of files.   Now there's only one in uix/slider.py.  If I miss a space, it will cleaned up the next batch of spacing updates.

**Comment by dessant** [comment]
Please run `make hook`, it is best to avoid committing errors, especially when we have a nice git hook for detecting them.

**Comment by merriam** [comment]
No.  Sorry.  It would break the github tools.

**Comment by dessant** [comment]
Closing this, ping us if you change your mind and commit the mentioned fixes on your branch, so we can reopen the pr.

**Comment by merriam** [comment]
OK, I'm pretty clear this has nothing to do with the code.  I have over
five pull requests sitting in limbo over spacing or semantics.   I cannot
do more work on Kivy with all the changes in limbo.

The pull requests submitted clearly improve the quality of Kivy, and you
seem to dervie some odd pleasure over trying to get your input into every
small piece.   I actually love to code, and find that part the enjoyable
portion of any contribution.  Quality improves as I touch the code, not
from constantly asking for permission for changes to be adopted.

What is it you hope to get out of your contributions to Kivy?

**Comment by dessant** [comment]
All I was asking the whole time (over and over) is to respect our contribution guide: http://kivy.org/docs/contribute.html#code-contributions.

The rest of your post shows a lack of respect towards those who spend time reviewing contributions, so i don't see a point in arguing over this topic.

**Pull request closed without merging**
