### PR TITLE
Config unicode support on Windows

### PR DESCRIPTION
**Pull request by SanAndreyas**
On Windows platform without this it cannot write correctly unicode characters

Maintainer merge checklist
* [ ] Title is descriptive/clear for inclusion in release notes.
* [ ] Applied a `Component: xxx` label.
* [ ] Applied the `api-deprecation` or `api-break` label.
* [ ] Applied the `release-highlight` label to be highlighted in release notes.
* [ ] Added to the milestone version it was merged into.
* [ ] **Unittests** are included in PR.
* [ ] Properly documented, including `versionadded`, `versionchanged` as needed.

### CODE REVIEW

**Review by matham — DISMISSED** [review]
Should be ok, I think. Currently it uses locale, but probably utf8 should be safe as a kivy default.

**Comment by tshirtman** [comment]
Shouldn't it also default reading the configuration to utf-8, for consistency?
Currently it defers to ConfigParser implementation, which does accept an optional encoding
https://docs.python.org/3/library/configparser.html#configparser.ConfigParser.read
and without it, default to the default for `open()` of which the docs says
>  if encoding is not specified the encoding used is platform-dependent: locale.getpreferredencoding(False) is called to get the current locale encoding
which probably won't cause any issue on linux/osx, but very much might on windows, as utf8 is not the default encoding.

**Comment by SanAndreyas** [comment]
@tshirtman your're 100% right. The following shall also be modified 'PythonConfigParser.read(self, filename, encoding="utf-8")' @ line 482.

**Review by matham — DISMISSED** [review]

**Comment by Berserker66** [comment]
I suggest to use "utf-8-sig" instead, which will correctly skip the BOM if present, and ignore it if not present.

**Comment by SanAndreyas** [comment]
utf-8-sig would be nice only for reading. But it looks kind of inconsistent to me to have the reading like utf-8-sig and the writing as utf-8

**Comment by matham** [comment]
>utf-8-sig would be nice only for reading. But it looks kind of inconsistent to me to have the reading like utf-8-sig and the writing as utf-8

I don't think we should generate the BOM. So I think writing with just utf8 is ok, even if reading is done with `utf-8-sig`. I don't think that's inconsistent. Rather, it makes the reading more robust.

**Review by matham — APPROVED** [review]

**Comment by misl6** [comment]
@matham I was checking the pending PRs marked as milestone `2.2.0` since we're approaching a feature freeze.
Anything is blocking us to merge this one?

**Pull request merged**
