### PR TITLE
Supporting multiline, Right-To-Left Persian/Arabic text rendering, via setting the rtl option for text

### PR DESCRIPTION
**Pull request by pylover**
This is just a snapshot of my works,

So, please review and say something about it.

The next step is to fix textinput cursor.

All comments and suggestions are appreciated.

### CODE REVIEW

**Comment by pylover** [comment]
Refer to: #1570

**Comment by akshayaurora** [comment]
- The way you have it implemented right now, the text can be either rtl or ltr.

The library that you use does support bi-directional features, that is we can have both kind of text in the same line. 

There is no need for the `rtl` property,  the text input should dynamically support any language based on input not based on how it is programmed.

This is the reason, this goes along with another topic, that is of font Glyph Fallback, 

- You are specifying arabic,  while we need to be able to support reshaping for all of the languages, not just for arabic.

**Comment by pylover** [comment]
Currently, i am searching for a library for reshaping to support all languages and cultures,

About rtl property, if so, we have a little process cost to detect language and direction. is it ok?

Or we can use a global config value?

**Comment by pylover** [comment]
In addition. most text rendering tools has an attribute about direction.

**Comment by pylover** [comment]
it seems the fribidi is enough

**Comment by tshirtman** [comment]
Hey, is this in a mergeable state? :)

**Comment by pylover** [comment]
No. Its just for review and comment about it. Its not mergable.
The fribidi complex text layout is supported. But its unstable
On Aug 22, 2016 5:55 AM, Gabriel Pettier <notifications@github.com> wrote:Hey, is this in a mergeable state? :)

**Comment by pylover** [comment]
Current problems:
1. After each space the cursor goes forward for one character.
2. kivy requires rtl now. should it be in setyp.py requirments?

**Comment by motad333** [comment]
hellow
i am begin to learn python and kivy
when i try to use your class some erorr happen and i cant fix it
No module named globalization
and when try to find it in core.text nothing not found 
what is it?

**Comment by pylover** [comment]
Checkout the `monkeypatch` branch from my fork.

**Comment by motad333** [comment]
hi again
i am very begin to python and when check your work was not found any file with monkeypath
what is easiest way to persian in textinput in kivy?
thank for answer

**Comment by KeyWeeUsr** [comment]
@pylover what is the license of `.ttf` files? I don't feel right about including random files to the repository.

**Comment by pylover** [comment]
@KeyWeeUsr, yes, this files are just for test, before, i mentioned to do not merge this pull request. this is only a try for rtl.

**Comment by engmms** [comment]
Hi pylover ,, Are you reach to solve arabic fonts problem in Python+Kivy App

**Comment by pylover** [comment]
@engmms, Yes, it's working partially, Needs some work about multiline-text selection and cursor location,

Unfortunately, I'm very busy at this time, but i'll continue a few months later.

**Comment by engmms** [comment]
How I can use it now,,as I build project and just I want to change
labels and buttons to appear with Arabic fonts

**Comment by pylover** [comment]
Just clone and build my fork

**Comment by eteamin** [comment]
@pylover Would you consider moving your pull request towards mergable state? thank you

**Comment by pylover** [comment]
Rebasing this pull request would not be a good idea. I think a from scratch try is so better, because the mainstream is changed a lot.

**Pull request closed without merging**
