### PR TITLE
Docs: fix typo in kivy.uix.image

### PR DESCRIPTION
**Pull request by mak8kammerer**
Removed unnecessary `-` in class rule (.kv)

Maintainer merge checklist
* [ ] Title is descriptive/clear for inclusion in release notes.
* [ ] Applied a `Component: xxx` label.
* [ ] Applied the `api-deprecation` or `api-break` label.
* [ ] Applied the `release-highlight` label to be highlighted in release notes.
* [ ] Added to the milestone version it was merged into.
* [ ] **Unittests** are included in PR.
* [ ] Properly documented, including `versionadded`, `versionchanged` as needed.

### CODE REVIEW

**Comment by pythonic64** [comment]
Why do you mean "-" in "<-FullImage>:" is a typo? Using "-" means don't include canvas instructions from "Image" class in canvas of "FullImage".

**Comment by mak8kammerer** [comment]
Wow! I don't know about this feature. Perhaps it should be mentioned in the documentation.

**Comment by Julian-O** [comment]
@mak8kammerer: I went to raise an issue saying this should be documented, but stopped when I found it was!

https://kivy.org/doc/stable/api-kivy.lang.html#redefining-a-widget-s-style

> Sometimes we would like to inherit from a widget in order to use its Python properties without also using its .kv defined style. For example, we would like to inherit from a Label, but we would also like to define our own canvas instructions instead of automatically using the canvas instructions inherited from the Label. We can achieve this by prepending a dash (-) before the class name in the .kv style definition.

**Comment by mak8kammerer** [comment]
It looks like I searched very badly. @Julian-O, thank you!

**Pull request closed without merging**
