### PR TITLE
Gridbug

### PR DESCRIPTION
**Pull request by andnovar**
This is a fix for GridLayout https://github.com/kivy/kivy/issues/3196 . It was tested using this code https://gist.github.com/tshirtman/df54d13618c71158ffe6 and the examples of gridlayout that comes with kivy. When repositioning elements in the grid the size of the widget is changed according to the calculated size, the problem is that since the size are the same halign and pos_hint don't work under this conditions. I avoided to calculate the size if any of the elements is None, in addition I calculate pos_hint such as in FloatLayout but with the calculated size of the cell.

### CODE REVIEW

**Comment by arlowhite** [comment]
When I was working on improving the Label documentation I created this example:
https://github.com/arlowhite/kivy/blob/label-text-size-doc/examples/widgets/label_texture_size.py
a8ad46b630896abbb46350d9b978a41d9c5b78d6

It has a bunch of Labels inside a GridLayout. I noticed that the GridLayout does not size its children correctly when you shrink the window and expand its width again. The GridLayout height is fixed, but the children in rows 1 & 3 change their heights as the Labels wrap and StackLayout rearranges buttons. The 2nd row of GridLayout children (2 Labels) is the only row where size_hint_y is not None. This row does not re-expand to fill all GridLayout space for some reason. Though it does grow a little bit.

**Comment by andnovar** [comment]
Do you have the code that triggers this issue ? I can take a look around this.

**Comment by arlowhite** [comment]
The file at this link:
https://github.com/arlowhite/kivy/blob/label-text-size-doc/examples/widgets/label_texture_size.py

Your gridlayout.py fixes the issue, but it logs a bunch of warnings as you resize:
> [WARNING] The value of rows_sh[row] is 1 shh 1
[WARNING] The value of cols_sh[col] is 1 shw 1
[WARNING] The value of cols_sh[col] is 1 shw 1
[WARNING] The value of cols_sh[col] is None shw 1
[WARNING] The value of cols_sh[col] is None shw 1
[WARNING] The value of cols_sh[col] is 1 shw 1
[WARNING] The value of rows_sh[row] is None shh 1
[WARNING] The value of cols_sh[col] is 1 shw 1
[WARNING] The value of rows_sh[row] is 1 shh 1

**Comment by andnovar** [comment]
Ow yes I need to remove those warnings. I will do it again once this pr is reviewed.

**Comment by arlowhite** [comment]
You probably should rebase your branch. 
> This branch is 2 commits ahead, 229 commits behind kivy:master 
https://github.com/kivy/kivy/compare/master...andnovar:gridbug
> Can't automatically merge.

I think just: git rebase -i upstream/master
And remove the merge commit.

**Comment by dessant** [comment]
Could you rebase and clean it up?

**Comment by dessant** [comment]
The underlying issue is being fixed, and the pr seems to be abandoned, closing.

**Pull request closed without merging**
