### PR TITLE
Fix PyInstaller hooks to work with v6.x.x #8653

### PR DESCRIPTION
**Pull request by ikus060**
Maintainer merge checklist
* [X] Title is descriptive/clear for inclusion in release notes.
* [ ] Applied a `Component: xxx` label.
* [ ] Applied the `api-deprecation` or `api-break` label.
* [ ] Applied the `release-highlight` label to be highlighted in release notes.
* [ ] Added to the milestone version it was merged into.
* [ ] **Unittests** are included in PR.
* [ ] Properly documented, including `versionadded`, `versionchanged` as needed.

### CODE REVIEW

**Comment by misl6** [comment]
Question (from someone not very into Windows development):
- Do we need to support `PyInstaller<6.0.0` ? (Consider Kivy is going to have a major release, so we can break things, if well documented)

**Comment by akshayaurora** [comment]
I would say considering the code to allow this is a few lines,  let the support for older pyinstaller be present for now. Maybe add a deprecated warning.. Can always remove/deprecate the support for older pyinstaller.

**Comment by ikus060** [comment]
@misl6 
> Do we need to support PyInstaller<6.0.0

Since Pyinstaller introduce a couple of breaking chance that might impact some application, I would consider preferable to keep compatibility with Pyinstaller v5 and v6

**Comment by misl6** [comment]
> @misl6
> 
> > Do we need to support PyInstaller<6.0.0
> 
> Since Pyinstaller introduce a couple of breaking chance that might impact some application, I would consider preferable to keep compatibility with Pyinstaller v5 and v6

Makes sense!

**Review by misl6 — APPROVED** [review]
LGTM. Thank you!

**Pull request merged**
