### PR TITLE
add modules/showborder

### PR DESCRIPTION
**Pull request by gottadiveintopython**
Shows widget's boundary. This kinda module is helpful for debug/test I think.

```python
from kivy.config import Config
Config.set('modules', 'showborder', '')
from kivy.lang import Builder
from kivy.app import runTouchApp


runTouchApp(Builder.load_string('''
GridLayout:
    padding: 10
    spacing: 10
    cols: 3
    Widget:
    EffectWidget:
    RelativeLayout:
    Scatter:
'''))
```
screenshot at 2018-10-20 20-05-21

~~But it doesn't work with ScrollView.~~ This issue was already fixed.

```python
from kivy.config import Config
Config.set('modules', 'showborder', '')
from kivy.lang import Builder
from kivy.app import runTouchApp


runTouchApp(Builder.load_string('''
GridLayout:
    padding: 10
    spacing: 10
    cols: 3
    Widget:
    Widget:
    ScrollView:
    Widget:
    Widget:
'''))
```

screenshot at 2018-10-20 20-08-20

### CODE REVIEW

**Comment by KeyWeeUsr** [comment]
It feels like deja vu, but I've seen this thing previously and have no clue where. Perhaps garden. Anyway, I love the idea!

**Comment by gottadiveintopython** [comment]
Thanks =)

**Comment by matham** [comment]
It's a really great idea. 

Can you test with e.g. Button that clears its previous rules? Also, I wonder how it'd look with a more complex app - can you post a screenshot from a more complex app, like the showcase in examples?

**Comment by gottadiveintopython** [comment]
@matham 

> Can you test with e.g. Button that clears its previous rules?

Do you mean test like this?

```python
from kivy.config import Config
Config.set('modules', 'showborder', '')
from kivy.lang import Builder
from kivy.app import runTouchApp


runTouchApp(Builder.load_string('''
#:import Window kivy.core.window.Window
#:import Modules kivy.modules.Modules
#:import Label kivy.uix.label.Label

BoxLayout:
    orientation: 'vertical'
    GridLayout:
        id: layout
        padding: 10
        spacing: 10
        cols: 6
    BoxLayout:
        padding: 10
        spacing: 10
        size_hint_y: .2
        Button:
            text: "add Label"
            on_press: layout.add_widget(Label(text='A'))
        Button:
            text: "activate 'showborder'"
            on_press: Modules.activate_module('showborder', Window)
        Button:
            text: "deactivate 'showborder'"
            on_press: Modules.deactivate_module('showborder', Window)
'''))
```

screenshot at 2018-10-21 23-49-33

>  can you post a screenshot from a more complex app, like the showcase in examples?

screenshot at 2018-10-21 23-46-42

**Comment by matham** [comment]
Ok, perfect. I mainly wanted to see if it works with buttons, because buttons clear their graphics instruction (https://github.com/kivy/kivy/blob/master/kivy/data/style.kv#L12). But it seems to work great.

Just one more thing, can you please listed in the docs here: https://github.com/kivy/kivy/blob/master/kivy/modules/__init__.py#L21.

**Comment by gottadiveintopython** [comment]
> buttons clear their graphics instruction

ah, I understand now.

`style.kv` is loaded when importing `kivy.lang`, and `showborder` loads kv rules after that. So it's probably fine.

https://github.com/kivy/kivy/blob/e767585e0c664c889a430bdf85b7c73749c195d1/kivy/lang/builder.py#L854

and thanks for the review.

**Pull request merged**
