### PR TITLE
Corrected upto PEP8 standard

### PR DESCRIPTION
**Pull request by saurabhiiit**

### CODE REVIEW

**Comment by dessant** [comment]
` examples/3Drendering/main.py` will not create a window if the import is removed, make sure the modules work after the changes.

I see you had a couple of pep8 prs in the past few days, if you intend to continue fixing pep8 issues, please batch your pep8 fixes and submit them in one pr.

**Comment by saurabhiiit** [comment]
Sorry for that I didn't noticed that,
sure, but the pep8 issues are very much can't be summed up in one PR as files structures are very big, thats why I solve it in a chunk .

**Comment by dessant** [comment]
I'm pretty sure they can be summed up, like this:
https://github.com/kivy/kivy/commit/856b305c0c876e53e802f1ac9ae16c21fa91ac1e

**Comment by saurabhiiit** [comment]
Thanks ... Yeah this could be done and I will take care of that .

**Comment by dessant** [comment]
Great, please open a new pr if you have other fixes.

**Pull request closed without merging**
