### PR TITLE
pep8 fixes

### PR DESCRIPTION
**Pull request by phunsukwangdu**
pep8 fixes were made which was generated by make style command

### CODE REVIEW

**Comment by KeyWeeUsr** [comment]
What about making a separate branch for each pull request? It's really not useful to always make pull request with every commit since you forked the kivy master branch. There are commits from the first color example you made.

**Comment by phunsukwangdu** [comment]
Yes i realised that and closed it.I am now making separate PRs for pep8 fixes.

**Comment by KeyWeeUsr** [comment]
Separate PR is _not enough_. You use `master` branch for **_all_** your commits and that's why it shows the commits like that. Seems like your color example was already merged, so the best thing for your `master` branch would be to do this:

    git reset HEAD~numberOfCommits
    git pull upstream master  # if kivy repo is named "upstream" in "git remote" list

Then some of the commits you already made would be fetched from the kivy repository to your local one. After that you should still have unstaged changes available. You should _separate_ them from `master` branch to another one this way:

    git checkout -b branchName
    git add .  # this adds all unstaged and new files

If your PR is merged, it's nice to sync your local repo with kivy repository. 🌵

**Comment by phunsukwangdu** [comment]
sure!! :) 
I had already done all this stuff just that i forgot to create new branch(my bad!).
A new pr #4814 is totally devoted for pep8 fixes. :)

**Pull request closed without merging**
