### PR TITLE
Fix issues #6226 and #6227 in multiline-enabled TextInput 

### LINKED ISSUE #6226: TextInput: text selection cancelled when scrolling with mousewheel
In TextInput, when scrolling text using mousewheel, text selection is removed. Checked on Windows and Ubuntu

```python
from kivy.app import App
from kivy.lang import Builder

KV = """
TextInput
    font_size: 20
    text: app.text
"""

class MyApp(App):
    def build(self):
        self.text = '\n'.join(['some text, line '+str(i) for i in range(200)])
        self.root = Builder.load_string(KV)

MyApp().run()
```

### LINKED ISSUE #6227: TextInput: cursor changes position when scrolling with mousewheel
In TextInput, when scrolling text using mousewheel, cursor changes position (row). Checked on Windows and Ubuntu

```python
from kivy.app import App
from kivy.lang import Builder

KV = """
TextInput
    font_size: 20
    text: app.text
"""

class MyApp(App):
    def build(self):
        self.text = '\n'.join(['some text, line '+str(i) for i in range(200)])
        self.root = Builder.load_string(KV)

MyApp().run()
```

### PR DESCRIPTION
**Pull request by vchslv13**
This pull request is assumed to address multiple issues related to TextInput, e.g. #6226, #6227, #5583 and so on. Currently it fixes issues #6226, #6227 in multiline-enabled mode, although proper testing for multiline-disabled mode and further code improvement is still needed.
If that's possible, I'd like to get the preliminary feedback about this PR, so I'd know whether I can continue the work as it goes or need to make some substantial changes in my approach.

Fixes #6226
Fixes #6227

### CODE REVIEW

**Comment by tito** [comment]
LGTM, in case you want to do more, it would be preferable to make multiple tiny PR than trying to fix and refactor more because you understand the code more. As it became harder to read and understand later.

Thanks also for the additionnal tests!

**Comment by vchslv13** [comment]
> LGTM

Great, I'll make a change or two now and will get the PR ready to be merged.

>  in case you want to do more, it would be preferable to make multiple tiny PR

OK. I wanted to make it all in one PR in order not to leave the TextInput in broken state between PRs. (E.g. if this PR is merged in current state, the TextInput with multiline=False will be broken until I fix it in the next PR).

> As it became harder to read and understand later.

I understand that, that's why I tried to make each commit self-explanatory, so that you could read changes by commit more easily. Sorry if it didn't turn out as planned.

> Thanks also for the additionnal tests!

You're welcome :)

**Comment by vchslv13** [comment]
I've renamed _height_for_x_lines_ to _ti_height_for_x_lines_, added docstring to it, rebased the branch on master.
If you're OK with what I said in previous comment, I hope the PR can be merged.

**Comment by vchslv13** [comment]
Hi @tito, any updates on the status of this PR?

**Comment by vchslv13** [comment]
Thank you @tito :)

**Pull request merged**
