### PR TITLE
Make EventDispatcher forward kwargs when it doesn't use it.

### LINKED ISSUE #3036: EventDispatcher eats up all kwargs even if it did not process it.
If any any of the kwargs are property names, EventDispatcher sets those property to the kwargs values. However, if the key is not a property, it does not forward it with super, but just eats it up.

For example:

```
from kivy.event import EventDispatcher
class MyColor(object):

    def __init__(self, color='blue', **kwargs):
        print 'color is {}'.format(color)

class Coloring(EventDispatcher, MyColor):
    pass

color = Coloring(color='green')
```
prints `color is blue`. rather than green.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/8607842-eventdispatcher-eats-up-all-kwargs-even-if-it-did-not-process-it?utm_campaign=plugin&utm_content=tracker%2F42681&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F42681&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by matham**
Fixes #3036 and reverts kivy/kivy#3094. This reverts the revert...

### CODE REVIEW

**Comment by dessant** [comment]
Can i merge and revert this?

**Comment by matham** [comment]
We basically need to make sure in every place not to call `super.__init__(**kw)` if `kw` contains non-prop keywords because they should have been eaten.

E.g. 
```py
    def __init__(self, **kw):
        super(Animation, self).__init__(**kw)

        # Initialize
        self._clock_installed = False
        self._duration = kw.get('d', kw.get('duration', 1.))
        self._transition = kw.get('t', kw.get('transition', 'linear'))
        self._step = kw.get('s', kw.get('step', 1. / 60.))
```
should be 
```py
    def __init__(self, duration=1., transition='linear', step=1. / 60., **kw):
        super(Animation, self).__init__(**kw)

        # Initialize
        self._clock_installed = False
        self._duration = kw.pop('d', duration)
        self._transition = kw.pop('t', transition)
        self._step = kw.pop('s', step)
```
This is something we'll have to fix everywhere because we have not been doing that correctly.

**Comment by matham** [comment]
Fixes Fixes #3036.

**Comment by akshayaurora** [comment]
@matham nice job!

**Comment by MoniaDev** [comment]
This still occurs when calling Popup().open(). With absolutely no arguments passed into the Popup at all.

File "C:/Users/Tomisin-PC/Desktop/CodeLexis/Services/Trail/Android/Trail_Android/test191.py", line 129, in <module>
     Popup()
   File "C:\Python34\lib\site-packages\kivy\uix\modalview.py", line 152, in __init__
     super(ModalView, self).__init__(**kwargs)
   File "C:\Python34\lib\site-packages\kivy\uix\anchorlayout.py", line 68, in __init__
     super(AnchorLayout, self).__init__(**kwargs)
   File "C:\Python34\lib\site-packages\kivy\uix\layout.py", line 72, in __init__
     super(Layout, self).__init__(**kwargs)
   File "C:\Python34\lib\site-packages\kivy\uix\widget.py", line 324, in __init__
     Builder.apply(self, ignored_consts=self._kwargs_applied_init)
   File "C:\Python34\lib\site-packages\kivy\lang.py", line 1970, in apply
     self._apply_rule(widget, rule, rule, ignored_consts=ignored_consts)
   File "C:\Python34\lib\site-packages\kivy\lang.py", line 2082, in _apply_rule
     child = cls(__no_builder=True)
   File "C:\Python34\lib\site-packages\kivy\uix\gridlayout.py", line 248, in __init__
     super(GridLayout, self).__init__(**kwargs)
   File "C:\Python34\lib\site-packages\kivy\uix\layout.py", line 72, in __init__
     super(Layout, self).__init__(**kwargs)
   File "C:\Python34\lib\site-packages\kivy\uix\widget.py", line 298, in __init__
     super(Widget, self).__init__(**kwargs)
   File "kivy\_event.pyx", line 254, in kivy._event.EventDispatcher.__init__ (kivy\_event.c:4895)
 TypeError: object.__init__() takes no parameters

**Pull request merged**
