### PR TITLE
EventLoopBase: Start/stop event loop only once

### PR DESCRIPTION
**Pull request by pythonic64**
Maintainer merge checklist
* [x] Title is descriptive/clear for inclusion in release notes.
* [x] Applied a `Component: xxx` label.
* [ ] Applied the `api-deprecation` or `api-break` label.
* [ ] Applied the `release-highlight` label to be highlighted in release notes.
* [x] Added to the milestone version it was merged into.
* [ ] **Unittests** are included in PR.
* [x] Properly documented, including `versionadded`, `versionchanged` as needed.

### CODE REVIEW

**Review by matham — APPROVED** [review]
Great! This should make things more bullet proof.

**Comment by matham** [comment]
The failing tests is due to the interaction between pyinstaller and pytest-cov. One of them must have updated and broke something.

**Comment by pythonic64** [comment]
Can we not use pyinstaller development version https://github.com/kivy/kivy/blob/master/.ci/windows_ci.ps1#L91?

**Comment by matham** [comment]
https://github.com/kivy/kivy/pull/7513 should resolve it. The issue is probably that the dev version I used had a problem.

**Comment by pythonic64** [comment]
Ok. I'll rebase once https://github.com/kivy/kivy/pull/7513 gets merged.

**Review by matham — APPROVED** [review]

**Pull request merged**
