### PR TITLE
Issue#4727:Image saving using 'save()' throws error-- resolved

### PR DESCRIPTION
**Pull request by saqib1707**
If data.fmt is not in ('rgba' ,'rgb') then change it to rgba using self.populate()

### CODE REVIEW

**Comment by udiboy1209** [comment]
Ahh, I see you made a PR! you should mention the issue number in the description so github automatically links the two: #4727 

See why the appveyor check failed and add the test I mentioned(on the issue) in the tests module, then this will be ready to merge!

**Comment by KeyWeeUsr** [comment]
@udiboy1209 appveyor is dead for now, just ignore it. The problem is basically because of missing yml file (and config), which is in my PR. There was probably a redirection from matham's account to the KivyOrg account and the yml is only in a separate branch waiting to be tested. The branch also kind of depends on py35 wheels (well, not necessarily), so that makes the delay a little bit longer.

It's going to resolve soon enough, but for testing Travis is the key. If Travis is ok with PR, it shouldn't break the tested stuff.

**Comment by KeyWeeUsr** [comment]
@saqib1707 Please remove `solution.py` file. It's not the test udiboy mentioned:

> add the test I mentioned(on the issue) in the tests module, then this will be ready to merge!

just a copied `kivy/core/image/__init__.py` with your fix, that's already present. Sorry for the confusion. 🙍

**Comment by akshayaurora** [comment]
@saqib1707 thanks. Nice fix.

**Pull request merged**
