### PR TITLE
Refactor _img_sdl2.pyx load_from_surface (cleanup)

### LINKED ISSUE #5269: Deceptive pixel format logic in _image_sdl2.pyx load_from_surface()
### Description

The intended happy path of converting to BGR888/ABGR8888 if ``image.format.BytesPerPixel`` is 3 or 4 is not reached. Instead, [this is the default execution path](https://github.com/kivy/kivy/blob/1.10.0/kivy/core/image/_img_sdl2.pyx#L76-L87). It seems like BPP=3 will not do any conversion, or incorrectly as ABGR if Rshift>Bshift. 

### Code and Logs

```python
fmt = 'rgb'
if fmt not in ('rgb', 'rgba'): # <------- suspect "not"
    if fmt == 'rgb':
```

https://github.com/kivy/kivy/blob/1.10.0/kivy/core/image/_img_sdl2.pyx#L63-L64

### PR DESCRIPTION
**Pull request by bionoid**
Closes #5269. This supersedes PR #5274, squashed to avoid commit spam + some minor cleanup (release gil during conversion, change order of some tests, added comments)

Summary of changes:

* Fix loading of SDL_PIXELFORMAT_BGR24 surfaces (BMP2, BMP3 images)
* Fix loading of (some) PNG formats with binary alpha
* Fix byte order for big-endian arch (untested)
* Some other surface formats were incorrectly handled, but not used by SDL_Image

Known issues:

* Some PNG48 images with binary transparency are still not loading correctly
* 8/16-bit grayscale PNGs are not supported. This seems like an issue with SDL_Image, it returns unexpected SDL_PIXELFORMAT_RGB565 instead of expected grayscale palette.

Details:

* Log of PR against test images: [link](https://gist.github.com/bionoid/ecb09b6db036faac77e4618fa9d82b2f) (100% pass)
* Log of original implementation with same images: [link](https://gist.github.com/bionoid/1738bce4170df332350a530b7a36553d) (AssertionError: _img_sdl2: 100 of 1832 tests failed, these are all BMP2/BMP3 images. Plus unreported failures, see below)
  * Some of the tested ``_BINARY`` (binary alpha) png files loaded here are reported with 'pass' but they don't "really" pass. The test doesn't mandate the returned pixel format, it just verifies that the pixels are consistent with the returned format. So these are  correctly converted to RGB, **but we lost alpha**
  * Hence, the PR test lists all ``_BINARY`` images as 'rgba', while 116 of them are incorrectly listed as "pass" with "rgb" above.

Tested formats (ImageMagick):

* Opaque: TIFF, BMP2, BMP3, PNG, GIF87
* Binary: GIF, PNG8, PNG24, PNG48, BMP
* Full Alpha: PNG32, PNG64, TGA

Notes:

* All formats above were tested with fully opaque pixels
* "Binary" and "Full Alpha" were tested with binary transparency
* "Full Alpha" were tested with the same images as for opaque, but semitransparent.
* TIFF is only tested as opaque, because the test doesn't support premultiplied alpha
* JPG not tested because pixel values are unpredictable (lossy compression)

### CODE REVIEW

**Comment by tito** [comment]
I didn't check the full code of the PR, but is there anything against a merge?

**Comment by bionoid** [comment]
Testing on windows/macos/android/ios remains to be done, although I am fairly confident it will work as they are all little-endian in practice (right?). Big-endian would be nice to test of course, but how? PowerPC? Can a bi-endian ARM be used, if so how? Does anyone have a working system? Is it possible to run kivy in big-endian qemu?

One issue does need clarification; the default conversion to RGB24 if no alpha channel is detected. That is technically best in terms of memory performance, but not obviously the best overall. SDL2 will pitch-align it to 4 bytes, which needs an OpenGL extension for unpacking (or we'll do it in software). But it'll likely be unpacked as 32bpp in the end, so the question is, would it be better to default to RGBA conversion, even if the image has no alpha information? I don't know...

All in all, I consider it a low-risk merge. As noted in previous issues, there are a several problems with the original implementation (the shift test, non-standard SDL_PixelFormat, no colorkey detection, dead code paths from the weird not, ...), and the ImageLoader test case (although far from perfect) speaks in favor of this implementation..

Unless 1.10.1 is planned for release shortly, merging is probably a good way to get it test it more widely?

**Comment by akshayaurora** [comment]
@bionoid any updates on this? is this ready to merger ?

**Comment by dolang** [comment]
Note to myself: try this together with #5785. I think the core dump happened in the SDL2 image provider when doing the screenshot test.

**Pull request merged**
