### PR TITLE
Add description to examples/3Drendering/main.py

### PR DESCRIPTION
**Pull request by merriam**

### CODE REVIEW

**Comment by dessant** [comment]
@merriam, nice addition, but why do you use multiple spaces between sentences? I've seen this in your previous prs too.
In case it is not intentional, displaying whitespace chars in your editor usually helps with catching consecutive ones.

**Comment by dessant** [comment]
Please remove the excessive space from the rest of your open prs too.

**Comment by merriam** [comment]
Hi dessant,

Thanks for you patience as you plow through the pull requests.  I'll move
to single space after periods for this project.   English used to be two
spaces, and now is in a gray area, and seems to be tending towards a single
space after a sentence. Currently about 1/3 of all U.S. residents do double
spacing.  http://en.wikipedia.org/wiki/Sentence_spacing has the annoyingly
long write up.

Then come the commas!  As some people say:  "They will pry the Oxford Comma
from my cold, dead, and decaying hands."

Have a great day,

Charles

**Comment by merriam** [comment]
Annoyingly, I find PEP8 mandates two spaces, so kivy should have a single
space explicit somewhere in the guidelines.  I'll see if I can have 'make
style' enforce this.


http://stackoverflow.com/questions/21571994/why-does-pep8-suggest-using-two-spaces-in-comments


Bleh.

Charles

On Fri, Jan 30, 2015 at 12:04 PM, Charles Merriam <charles.merriam@gmail.com

**Comment by dessant** [comment]
Never noticed that pep8 rule, i guess we need to add it to our imaginary list of pep8 sins.

**Comment by merriam** [comment]
So what's really on your mind?   If you are halting all my PRs based on
one-or-two spaces, I wonder if I rubbed you the wrong way.   All is good?
 -- Charles

**Comment by dessant** [comment]
Yes, of course, everything is ok ;). We don't use three spaces between sentences in our docstrings, but one. If we merge it like this, @zencode will likely spend his time rediscovering and deleting those spaces. It is always better to make these trivial fixes before merging a pr.

We should probably write a guideline for this. I'm glad you are contributing and I'm looking forward to your new prs.

**Comment by merriam** [comment]
Hi dessant,

I fixed the 'make style' to flag these issues. Sentences.  Like.  This.
also blanks line at the end of the file.

Would you just merge the PRs with the problem?   I'll then submit a new PR
fixing all these spacing issues in one commit, without spending an hour or
two fighting with git.   If its any consolation, I make 'make style' a lot
cleaner than it had been by fixing other issues.

Have a great day!

Charles

**Comment by dessant** [comment]
Sure, merging them now, thanks for everything so far.

**Pull request merged**
