### PR TITLE
Implementing #944 (Feature request: texture rotation)

### PR DESCRIPTION
**Pull request by victor-rene**
I didn't implement the rotate function, as described in #944. Something about it seems off.
While it makes sense to have a generic rotate function, I don't like introducing confusing behavior.
Better to keep each function separate and call them as needed.

### CODE REVIEW

**Comment by snapy666** [comment]
I agree with @victor-rene, despite having made the proposal for the general `rotate` function.

In praxis one would probably not use integers such as `(0, 90, 180, 270)`, but `(0, 1, 2, 3)` or, if the texture is an arrow, `('left', 'right', 'top', 'down')`. Also, writing such a mapping is trivial.

**Comment by CreamyCookie** [comment]
@victor-rene Any news on this? Maybe you could modify this pull request to remove the generic rotate function..

**Comment by CreamyCookie** [comment]
@inclement Have you thought about the naming?

I think adding a generic `rotate` function is a bad idea. (One can easily write such a mapping, or use an if-else-if-chain.)

**Comment by Zen-CODE** [comment]
This issue was already addressed with this merge: https://github.com/kivy/kivy/pull/1996

Thanks anyway :-)

**Pull request closed without merging**
