### PR TITLE
Update lang.rst

### PR DESCRIPTION
**Pull request by emon10005**
Mention widget naming requirements #3739

### CODE REVIEW

**Comment by inclement** [comment]
Thanks for the contribution!

The specific requirement is that widgets start with a capital letter (and that properties do not) if they are to work when manipulated via kv language. Would you be able to modify your change to make this clear, since it isn't actually pep8 itself that has to be followed?

**Comment by emon10005** [comment]
should i not mention pep8

**Comment by inclement** [comment]
You could recommend it in the context of being a worthwhile style guide
to adhere to in any case, but I don't think it's essential.

**Comment by dessant** [comment]
@emon10005, it is a good start, thanks a lot! :+1:

**Pull request merged**
