### PR TITLE
Updated ES vkeyboard layout to resemble a real ES keyboard layout

### PR DESCRIPTION
**Pull request by schoolsplay**
This layout is based on a real Spanish keyboard, this one:
PXL_20231223_080554376

These are the normal, shift and special layouts (theming is our own)
The special layout has extra Spanish letters as we can't combine keys as one would do on a hardware keyboard.
The layouts are checked by our Spanish colleagues and the special layout with the predefined Spanish characters is how we use it. Feel free to make any changes you see fit.

Screenshot from 2023-12-28 13-44-05
Screenshot from 2023-12-28 13-43-39
Screenshot from 2023-12-28 13-43-17

Maintainer merge checklist
* [ ] Title is descriptive/clear for inclusion in release notes.
* [ ] Applied a `Component: xxx` label.
* [ ] Applied the `api-deprecation` or `api-break` label.
* [ ] Applied the `release-highlight` label to be highlighted in release notes.
* [ ] Added to the milestone version it was merged into.
* [ ] **Unittests** are included in PR.
* [ ] Properly documented, including `versionadded`, `versionchanged` as needed.

### CODE REVIEW

**Comment by Julian-O** [comment]
I've been invited to review, but I want to acknowledge, I am way out of my depth. I am not a Spanish speaker, and don't know the limitations of the Kivy keyboards.

It should behave like other soft keyboards. I don't know what the Android nor iPhone soft keyboards are like for Spanish, but I brought up the Windows 11 Spanish soft keyboard for comparison.

> The special layout has extra Spanish letters as we can't combine keys as one would do on a hardware keyboard.

The way the keys combine on the Windows 11 keyboard is the acute button is hit first, and then the appropriate vowel. Upper-case is achieved by holding shift key. Pressing shift before hitting the acute accent gives the diaresis.

It seems to me that this should be possible, by making the accent into the mode change ["special"] button. Then the vowels can simply be placed where they normally would be on a qwerty keyboard, rather than in a row, and using shift to alternate between upper and lower case.

Have I misunderstood the capabilities of the Kivy keyboard?

**Comment by schoolsplay** [comment]
With all due respect, its only a Spanish layout json. It has nothing to do with how the keyboard widget behaves.
It is just a way to map the keys, nothing more.
If you want address issues with the keyboard you should open a bug report against the vkeyboard widget.

We are an international business with, among others, a Spanish department located in spain with native speakers. They provided me with the hardware keyboard you see in the photograph and the windows/gnome key layout it should generate.
They reviewed the kivy vkeyboard with this Spanish layout and are using it as we speak in our product.

**Comment by Julian-O** [comment]
You clearly have more experience with using it, which counts for a lot.

I was arguing that the existing widget functionality should provide for a better experience with appropriate layout configuration. At some point, a bird in the hand is worth two in the bush.

**Comment by akshayaurora** [comment]
As the layout now matches the native keyboard on the image, let's merge this. Issues with vkeyboard widget itself can be worked on with a separate pr.

@schoolsplay thanks for all your efforts.

**Review by akshayaurora — APPROVED** [review]

**Pull request merged**
