### PR TITLE
Fixes #3254: Setting multisamples in SDL2

### LINKED ISSUE #3254: Setting multisampling samples in SDL2 missing
Like in the pygame window provider there should be code in the SDL2 provider that sets the number of samples for multisampling. This could be done either in create_window() in window_sdl2.py or in setup_window() in _window_sdl2.pyx.

In setup_window() in _window_sdl2.pyx it could be something like this:
```python
multisamples = Config.getint('graphics', 'multisamples')

if multisamples > 0:
    SDL_GL_SetAttribute(SDL_GL_MULTISAMPLEBUFFERS, 1)
    SDL_GL_SetAttribute(SDL_GL_MULTISAMPLESAMPLES, multisamples)
```

It probably has to be before  "self.win = SDL_CreateWindow(...)".

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/10732282-setting-multisampling-samples-in-sdl2-missing?utm_campaign=plugin&utm_content=tracker%2F42681&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F42681&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by luminosuslight**
Enables multisampling with SDL2 as the window provider.
More than 8 multisampling samples lead to crashes, so it is limited to 8.

Fixes this bug: #3254

### CODE REVIEW

**Comment by dessant** [comment]
There must be a better way than limiting like this. Could you post the full error log? Does your video card support more than 8?

**Comment by luminosuslight** [comment]
This is the log with multisamples set to 16:

```shell
[INFO              ] Logger: Record log in /home/tim/.kivy/logs/kivy_15-05-14_0.txt
[INFO              ] Kivy: v1.9.1-dev
[INFO              ] Python: v2.7.9 (default, Apr  2 2015, 15:33:21) 
[GCC 4.9.2]
[INFO              ] Factory: 175 symbols loaded
[INFO              ] Image: Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO              ] Text: Provider: sdl2
[INFO              ] OSC: using <multiprocessing> for socket
[INFO              ] Window: Provider: sdl2(['window_egl_rpi'] ignored)
[CRITICAL          ] Window: Unable to find any valuable Window provider at all!
egl_rpi - ImportError: cannot import name bcm
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/__init__.py", line 57, in core_select_lib
    fromlist=[modulename], level=0)
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/window_egl_rpi.py", line 12, in <module>
    from kivy.lib.vidcore_lite import bcm, egl

sdl2 - RuntimeError: Couldn't find matching GLX visual
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/__init__.py", line 65, in core_select_lib
    cls = cls()
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 137, in __init__
    super(WindowSDL, self).__init__()
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/__init__.py", line 616, in __init__
    self.create_window()
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 187, in create_window
    self.fullscreen, resizable, state)
  File "kivy/core/window/_window_sdl2.pyx", line 86, in kivy.core.window._window_sdl2._WindowSDL2Storage.setup_window (kivy/core/window/_window_sdl2.c:1629)
  File "kivy/core/window/_window_sdl2.pyx", line 22, in kivy.core.window._window_sdl2._WindowSDL2Storage.die (kivy/core/window/_window_sdl2.c:966)

x11 - ImportError: No module named window_x11
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/__init__.py", line 57, in core_select_lib
    fromlist=[modulename], level=0)

[CRITICAL          ] App: Unable to get a Window, abort.
[WARNING           ] stderr: Exception SystemExit: 1 in 'kivy.properties.dpi2px' ignored
```
With multisamples set to 8 it works as expected.
My graphics card is an AMD Radeon R7 260X, if I remeber correctly with Pygame as the window provider 16 multisampling samples worked.
The SDL2 doc says: "Typical values are 2 and 4.".

**Comment by dessant** [comment]
It crashes for me with the same error, even if i don't set multisamples.

**Comment by luminosuslight** [comment]
Hmm, here is someone with the same problem: http://stackoverflow.com/questions/24738638/how-to-determine-the-maximum-number-of-supported-multisample-samples

Maybe this was the reason why nobody integrated it before in kivy. But I think anti-aliasing is a very important feature that should not be rejected because some video cards can't handle it with SDL2.
We could try to create the window on the first start with multisampling set to 8, then decrease the number till it works and cache the value for the next start somewhere.

**Comment by luminosuslight** [comment]
The last commit is a quit ugly workaround where it falls back to no multisampling if the window can't be created with multisampling and the number of samples is limited to 4.
But as this should work on all systems it could be a good compromise to no multisampling at all.

**Comment by tito** [comment]
I'll +1 this PR, as this is a behavior we were having before for Pygame. If no multisamples was working, we were trying without.

**Comment by tito** [comment]
@dessant if the latest version of this PR does work for you, then feel free to merge :)

**Comment by akshayaurora** [comment]
@luminosuslight thanks for the fix.

**Pull request merged**
