### PR TITLE
PEP 621: Migrate settings from setup.cfg into pyproject.toml

### PR DESCRIPTION
**Pull request by cclauss**
Migrate settings from `setup.cfg` into `pyproject.toml` using [ini2toml](https://pypi.org/project/ini2toml) to do the file conversion and running [pyproject-fmt](https://pypi.org/project/pyproject-fmt) and then [validate-pyproject](https://github.com/abravalheri/validate-pyproject) in pre-commit to validate the results.
* Currently, flake8 is not yet compatible with `pyproject.toml` so leave its settings in `setup.cfg`.

Maintainer merge checklist
* [x] Title is descriptive/clear for inclusion in release notes.
* [ ] Applied a `Component: xxx` label.
* [ ] Applied the `api-deprecation` or `api-break` label.
* [ ] Applied the `release-highlight` label to be highlighted in release notes.
* [ ] Added to the milestone version it was merged into.
* [ ] **Unittests** are included in PR.
* [ ] Properly documented, including `versionadded`, `versionchanged` as needed.

### CODE REVIEW

**Comment by misl6** [comment]
Hi @cclauss !

I was thinking about migrating to `pyproject.toml` (to keep the project up-to-date and for `dependabot`), and I've found this PR, but that has been closed just 3 days after the initial commit.

Did you close it by mistake? If yes, are you still interested to propose this changes?

**Comment by cclauss** [comment]
I cannot remember why I closed it.  If you want, I can try to recreate it tomorrow.

**Comment by misl6** [comment]
>  If you want, I can try to recreate it tomorrow
Sound good!  😀

**Comment by cclauss** [comment]
Unfortunately there is way too much logic built into the 1,300+ lines of [`setup.py`](https://github.com/kivy/kivy/blob/master/setup.py).  The commands like [`setup.py install`, `setup.py build_ext`, `setup.py build_factory`](https://github.com/search?q=repo%3Akivy%2Fkivy%20setup.py) are all [deprecated](https://setuptools.pypa.io/en/latest/userguide/quickstart.html#setuppy-discouraged).  It would take a fair amount of work to make this transition.

**Pull request closed without merging**
