### PR TITLE
Optimize PNG images losslessly via Google's zopflipng

### PR DESCRIPTION
**Pull request by PeterDaveHello**
101 PNG images re-compressed losslessly as below :tada: which makes the release smaller and loading faster :rocket: 
```
 kivy/data/glsl/default.png                                        | Bin 224 -> 74 bytes
 kivy/data/images/cursor.png                                       | Bin 386 -> 138 bytes
 kivy/data/images/defaultshape.png                                 | Bin 9345 -> 4053 bytes
 kivy/data/images/defaulttheme-0.png                               | Bin 65052 -> 54001 bytes
 kivy/data/images/testpattern.png                                  | Bin 178 -> 73 bytes
 kivy/data/logo/kivy-icon-128.png                                  | Bin 3229 -> 3186 bytes
 kivy/data/logo/kivy-icon-16.png                                   | Bin 420 -> 392 bytes
 kivy/data/logo/kivy-icon-24.png                                   | Bin 614 -> 538 bytes
 kivy/data/logo/kivy-icon-256.png                                  | Bin 7435 -> 7329 bytes
 kivy/data/logo/kivy-icon-32.png                                   | Bin 825 -> 724 bytes
 kivy/data/logo/kivy-icon-48.png                                   | Bin 1169 -> 1046 bytes
 kivy/data/logo/kivy-icon-64.png                                   | Bin 1616 -> 1468 bytes
 kivy/tests/test_button.png                                        | Bin 5315 -> 4936 bytes
 kivy/tools/theming/defaulttheme/action_bar.png                    | Bin 181 -> 86 bytes
 kivy/tools/theming/defaulttheme/action_group.png                  | Bin 306 -> 181 bytes
 kivy/tools/theming/defaulttheme/action_group_disabled.png         | Bin 284 -> 168 bytes
 kivy/tools/theming/defaulttheme/action_group_down.png             | Bin 455 -> 330 bytes
 kivy/tools/theming/defaulttheme/action_item.png                   | Bin 180 -> 82 bytes
 kivy/tools/theming/defaulttheme/action_item_down.png              | Bin 164 -> 96 bytes
 kivy/tools/theming/defaulttheme/action_view.png                   | Bin 180 -> 82 bytes
 kivy/tools/theming/defaulttheme/audio-volume-high.png             | Bin 936 -> 528 bytes
 kivy/tools/theming/defaulttheme/audio-volume-low.png              | Bin 753 -> 425 bytes
 kivy/tools/theming/defaulttheme/audio-volume-medium.png           | Bin 831 -> 478 bytes
 kivy/tools/theming/defaulttheme/audio-volume-muted.png            | Bin 856 -> 477 bytes
 kivy/tools/theming/defaulttheme/bubble.png                        | Bin 535 -> 332 bytes
 kivy/tools/theming/defaulttheme/bubble_arrow.png                  | Bin 307 -> 179 bytes
 kivy/tools/theming/defaulttheme/bubble_btn.png                    | Bin 179 -> 96 bytes
 kivy/tools/theming/defaulttheme/bubble_btn_pressed.png            | Bin 276 -> 178 bytes
 kivy/tools/theming/defaulttheme/button.png                        | Bin 336 -> 190 bytes
 kivy/tools/theming/defaulttheme/button_disabled.png               | Bin 330 -> 182 bytes
 kivy/tools/theming/defaulttheme/button_disabled_pressed.png       | Bin 333 -> 222 bytes
 kivy/tools/theming/defaulttheme/button_pressed.png                | Bin 331 -> 223 bytes
 kivy/tools/theming/defaulttheme/checkbox_disabled_off.png         | Bin 278 -> 158 bytes
 kivy/tools/theming/defaulttheme/checkbox_disabled_on.png          | Bin 505 -> 296 bytes
 kivy/tools/theming/defaulttheme/checkbox_off.png                  | Bin 329 -> 121 bytes
 kivy/tools/theming/defaulttheme/checkbox_on.png                   | Bin 1237 -> 1092 bytes
 kivy/tools/theming/defaulttheme/checkbox_radio_disabled_off.png   | Bin 464 -> 213 bytes
 kivy/tools/theming/defaulttheme/checkbox_radio_disabled_on.png    | Bin 684 -> 429 bytes
 kivy/tools/theming/defaulttheme/checkbox_radio_off.png            | Bin 438 -> 225 bytes
 kivy/tools/theming/defaulttheme/checkbox_radio_on.png             | Bin 1066 -> 693 bytes
 kivy/tools/theming/defaulttheme/close.png                         | Bin 1306 -> 1095 bytes
 kivy/tools/theming/defaulttheme/filechooser_file.png              | Bin 3055 -> 2752 bytes
 kivy/tools/theming/defaulttheme/filechooser_folder.png            | Bin 3514 -> 3211 bytes
 kivy/tools/theming/defaulttheme/filechooser_selected.png          | Bin 3338 -> 2932 bytes
 kivy/tools/theming/defaulttheme/image-missing.png                 | Bin 814 -> 434 bytes
 kivy/tools/theming/defaulttheme/media-playback-pause.png          | Bin 292 -> 134 bytes
 kivy/tools/theming/defaulttheme/media-playback-start.png          | Bin 478 -> 279 bytes
 kivy/tools/theming/defaulttheme/media-playback-stop.png           | Bin 292 -> 136 bytes
 kivy/tools/theming/defaulttheme/modalview-background.png          | Bin 836 -> 700 bytes
 kivy/tools/theming/defaulttheme/overflow.png                      | Bin 215 -> 99 bytes
 kivy/tools/theming/defaulttheme/player-background.png             | Bin 2936 -> 2129 bytes
 kivy/tools/theming/defaulttheme/player-play-overlay.png           | Bin 6074 -> 4620 bytes
 kivy/tools/theming/defaulttheme/previous_normal.png               | Bin 354 -> 204 bytes
 kivy/tools/theming/defaulttheme/progressbar.png                   | Bin 836 -> 692 bytes
 kivy/tools/theming/defaulttheme/progressbar_background.png        | Bin 225 -> 123 bytes
 kivy/tools/theming/defaulttheme/ring.png                          | Bin 3742 -> 2204 bytes
 kivy/tools/theming/defaulttheme/selector_left.png                 | Bin 4402 -> 3704 bytes
 kivy/tools/theming/defaulttheme/selector_middle.png               | Bin 4373 -> 3759 bytes
 kivy/tools/theming/defaulttheme/selector_right.png                | Bin 4403 -> 3699 bytes
 kivy/tools/theming/defaulttheme/separator.png                     | Bin 121 -> 72 bytes
 kivy/tools/theming/defaulttheme/slider_cursor.png                 | Bin 2433 -> 1842 bytes
 kivy/tools/theming/defaulttheme/slider_cursor_disabled.png        | Bin 2510 -> 1803 bytes
 kivy/tools/theming/defaulttheme/sliderh_background.png            | Bin 206 -> 115 bytes
 kivy/tools/theming/defaulttheme/sliderh_background_disabled.png   | Bin 206 -> 114 bytes
 kivy/tools/theming/defaulttheme/sliderv_background.png            | Bin 234 -> 131 bytes
 kivy/tools/theming/defaulttheme/sliderv_background_disabled.png   | Bin 232 -> 130 bytes
 kivy/tools/theming/defaulttheme/spinner.png                       | Bin 391 -> 229 bytes
 kivy/tools/theming/defaulttheme/spinner_disabled.png              | Bin 380 -> 216 bytes
 kivy/tools/theming/defaulttheme/spinner_pressed.png               | Bin 386 -> 282 bytes
 kivy/tools/theming/defaulttheme/splitter.png                      | Bin 313 -> 162 bytes
 kivy/tools/theming/defaulttheme/splitter_disabled.png             | Bin 316 -> 127 bytes
 kivy/tools/theming/defaulttheme/splitter_disabled_down.png        | Bin 593 -> 311 bytes
 kivy/tools/theming/defaulttheme/splitter_disabled_down_h.png      | Bin 559 -> 291 bytes
 kivy/tools/theming/defaulttheme/splitter_disabled_h.png           | Bin 309 -> 134 bytes
 kivy/tools/theming/defaulttheme/splitter_down.png                 | Bin 639 -> 515 bytes
 kivy/tools/theming/defaulttheme/splitter_down_h.png               | Bin 606 -> 479 bytes
 kivy/tools/theming/defaulttheme/splitter_grip.png                 | Bin 222 -> 107 bytes
 kivy/tools/theming/defaulttheme/splitter_grip_h.png               | Bin 192 -> 103 bytes
 kivy/tools/theming/defaulttheme/splitter_h.png                    | Bin 328 -> 183 bytes
 kivy/tools/theming/defaulttheme/switch-background.png             | Bin 1113 -> 737 bytes
 kivy/tools/theming/defaulttheme/switch-background_disabled.png    | Bin 1027 -> 481 bytes
 kivy/tools/theming/defaulttheme/switch-button.png                 | Bin 313 -> 181 bytes
 kivy/tools/theming/defaulttheme/switch-button_disabled.png        | Bin 303 -> 179 bytes
 kivy/tools/theming/defaulttheme/tab.png                           | Bin 2923 -> 2794 bytes
 kivy/tools/theming/defaulttheme/tab_btn.png                       | Bin 3220 -> 2921 bytes
 kivy/tools/theming/defaulttheme/tab_btn_disabled.png              | Bin 3079 -> 2858 bytes
 kivy/tools/theming/defaulttheme/tab_btn_disabled_pressed.png      | Bin 3206 -> 3033 bytes
 kivy/tools/theming/defaulttheme/tab_btn_pressed.png               | Bin 3357 -> 3101 bytes
 kivy/tools/theming/defaulttheme/tab_disabled.png                  | Bin 2919 -> 2773 bytes
 kivy/tools/theming/defaulttheme/textinput.png                     | Bin 612 -> 394 bytes
 kivy/tools/theming/defaulttheme/textinput_active.png              | Bin 498 -> 408 bytes
 kivy/tools/theming/defaulttheme/textinput_disabled.png            | Bin 691 -> 382 bytes
 kivy/tools/theming/defaulttheme/textinput_disabled_active.png     | Bin 431 -> 254 bytes
 kivy/tools/theming/defaulttheme/tree_closed.png                   | Bin 557 -> 277 bytes
 kivy/tools/theming/defaulttheme/tree_opened.png                   | Bin 532 -> 266 bytes
 kivy/tools/theming/defaulttheme/vkeyboard_background.png          | Bin 720 -> 290 bytes
 kivy/tools/theming/defaulttheme/vkeyboard_disabled_background.png | Bin 739 -> 291 bytes
 kivy/tools/theming/defaulttheme/vkeyboard_disabled_key_down.png   | Bin 1022 -> 836 bytes
 kivy/tools/theming/defaulttheme/vkeyboard_disabled_key_normal.png | Bin 934 -> 744 bytes
 kivy/tools/theming/defaulttheme/vkeyboard_key_down.png            | Bin 1029 -> 891 bytes
 kivy/tools/theming/defaulttheme/vkeyboard_key_normal.png          | Bin 951 -> 745 bytes
```

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@akshayaurora do you have any reference about the "more compute intensive decompression time" part? Thanks.

**Comment by PeterDaveHello** [comment]
https://en.wikipedia.org/wiki/Zopfli
> The speed of decompressing Zopfli's output versus zlib's output is practically unaffected.

**Comment by dessant** [comment]
Let's reopen until someone can review it.

**Comment by tito** [comment]
After reading resources, compression time is much much slower than gzip-png, but the decompression time is the same. It's a go for me!

**Pull request merged**
