### PR TITLE
Correctly transform touch_up position

### PR DESCRIPTION
**Pull request by johanneshk**
See issue #4477

### CODE REVIEW

**Comment by inclement** [comment]
I notice you mention in the linked issue that it might have some issues - did you work out what was going on there?

**Comment by johanneshk** [comment]
@inclement Yes, the FileChooserListView somehow changes (can't really describe: Some clicks seem to go missing, opens wrong folders, slower). See this Gist: https://gist.github.com/johanneshk/5bfa9a3983e81a20ed16ed1ff0d80257#file-main2-py

This PR seems to fix the initial behavior, but for some reason the FilechooserListView is broken (at least for me?). I don't know why, but that's what I'm experiencing...

**Comment by johanneshk** [comment]
Could someone confirm my Edit above? Plus maybe the behavior in general? If this is correct, I could go ahead and look into FileChooserListView and why it behaves differently.

Thanks!

**Comment by matham** [comment]
At a first glance you're correct. Because `_do_touch_up` is `"called"` from `on_scroll_stop` which receives touches in parent coordinates, not window coordinates. So `to_local` rather than `to_widget` should be used. That is your reasoning, right?

The problem with this though is that it's `"scheduled"`, not called from `on_scroll_stop`. So in between the scheduling, when it's in parent coordinates, and the execution; the touch is likely to have been converted back to window coordinates. That's because he touch starts and ends in window coordinates.

At least this is how I understand this.

**Comment by johanneshk** [comment]
@matham  your explanation makes perfect sense. Plus the first comment in '_do_touch_up' is 'touch is in window coords'. With the pop statements you added this now seems to be true in all cases.

So please don't merge this PR but rather #4508 .

**Pull request closed without merging**
