### PR TITLE
Slider cursor size

### PR DESCRIPTION
**Pull request by ElliotGarbus**
Allows the cursor size to scale up to fit the defined cursor size.

image

Using the current definition of a slider, high resolution images are scaled down to the cursor size, but low resolution images are not scaled up to the cursor size.  The image above shows the impact on MacOS.  I noticed this issue when I created 32x32 images targeting Windows.  When moving to MacOS the cursors did not scale to the higher resolution.  In the image above the top row highlights the issue, and the second row shows the fix.  The code below generated the image:
```Python
from kivy.app import App
from kivy.lang import Builder

kv = '''
<StretchSlider@Slider>:
    Image:
        pos: (root.value_pos[0] - root.cursor_width / 2, root.center_y - root.cursor_height / 2) if root.orientation == 'horizontal' else (root.center_x - root.cursor_width / 2, root.value_pos[1] - root.cursor_height / 2)
        size: root.cursor_size 
        source: root.cursor_disabled_image if root.disabled else root.cursor_image
        allow_stretch: True

<ComboSlider@BoxLayout>:
    orientation: 'vertical'
    cursor_image: ''
    text: ''
    BoxLayout:
        orientation: 'vertical'
        Slider:
            orientation: 'vertical'
            cursor_image: root.cursor_image
        Label:
            size_hint_y: .1
            text: root.text

<ComboStretchSlider@BoxLayout>:
    orientation: 'vertical'
    cursor_image: ''
    text: ''
    BoxLayout:
        orientation: 'vertical'
        StretchSlider:
            orientation: 'vertical'
            cursor_image: root.cursor_image
        Label:
            size_hint_y: .1
            text: root.text
        
BoxLayout:
    orientation: 'vertical'
    Label:
        size_hint_y:.1
        text: 'Original'
        font_size: '20sp'
    BoxLayout:
        ComboSlider:
            cursor_image: 'cursor_16.png'
            text: '16x16'
        ComboSlider:
            cursor_image: 'cursor_32.png'
            text: '32x32'
        ComboSlider:
            cursor_image: 'cursor_64.png'
            text: '64x64'   
        ComboSlider:
            cursor_image: 'cursor_128.png'
            text: '128x128'               
    Label:
        size_hint_y:.4
        text: 'Allow Stretch'
        font_size: '20sp'
    BoxLayout:
        ComboStretchSlider:
            cursor_image: 'cursor_16.png'
            text: '16x16'
        ComboStretchSlider:
            cursor_image: 'cursor_32.png'
            text: '32x32'
        ComboStretchSlider:
            cursor_image: 'cursor_64.png'
            text: '64x64'
        ComboStretchSlider:
            cursor_image: 'cursor_128.png'
            text: '128x128'
'''


class SliderCursorSizeApp(App):

    def build(self):
        return Builder.load_string(kv)


SliderCursorSizeApp().run()
```

### CODE REVIEW

**Comment by Zen-CODE** [comment]
This looks like a nice improvement, but please could you update the PR to resolve conflicts.

Secondly, the example gives the errors re missing image: `[ERROR  ] [Image       ] Not found <cursor_128.png>`, so it's not clear from the example what effect this had on standard kivy cursors. An example which demonstrates that might be more useful?

Still, that's a minor one. We can test using standard examples, but please resolve the conflicts. Thanks :+1:

**Comment by Zen-CODE** [comment]
Hmm. On further examination, this change would contradict the `cursor_width` / `cursor_height` proprieties, which set them via `sp` units...

https://kivy.org/doc/stable/api-kivy.uix.slider.html#kivy.uix.slider.Slider.cursor_height

If we were to incorporate dynamic sizing, we'd need to update those docs accordingly....

**Comment by ElliotGarbus** [comment]
In practice I found it was better to use a higher resolution for the cursor image for the Mac.   Adding 'allow_stretch', made results quick - but the loss in image quality was ultimately not acceptable (to me).  There are a number of spots where things just need to be different on MacOS, to accommodate the higher resolution.  

Let me know if you'd like me the to close this PR.

**Comment by Zen-CODE** [comment]
Agreed. The high-res retina displays definitely expose the lower quality images, so I see the value in this work.

Perhaps a good compromise to move this into an example (in the examples folder) with the images and required resources? The thinking is to build a small example app of how to replace the lower quality graphics with higher quality ones for MacOS? How does that would?

**Comment by Zen-CODE** [comment]
Or add a `stretch' property that we document as allowing the cursor size to be dynamically determind?

**Comment by AndiEcker** [comment]
I thought this change got already added to master via #6859 (see
https://github.com/kivy/kivy/pull/6859)

Am Mi., 21. Okt. 2020 um 08:11 Uhr schrieb Richard Larkin <
notifications@github.com>:

**Comment by Zen-CODE** [comment]
Indeed! You are spot on. Thanks @AndiEcker

**Pull request closed without merging**
