### PR TITLE
more general css selectors for kv rules

### PR DESCRIPTION
**Pull request by denys-duchier**
I would like some feedback on a prototype for a pure extension to kv-lang introducing css-like contextual selectors for kv rules. 

The new contextual rule selectors are enclosed in `<< ... >>` which makes them entirely separate from existing selectors.  Here is an example selector:

```
 <<A B.p1.p2 > C *#i3>>
```

Such a rule applies to any (`*`) widget with `id=i3`, that is a descendant of a widget whose Python class inherits from `C`, which itself is an immediate child of a widget whose python class inherits from `B` and whose `cls` property has elements `p1`and `p2`, and which itself is a descendant of a widget whose Python
class inherits from `A`.

Since widgets get their properties constrained fairly late in the build process, contextual selection uses statically evaluable properties `id` and `cls` of rules whenever possible and as early as possible.

An advantage of this extension is that you can more easily modularize your design: you can provide a common pattern as a rule that is instantiated many time, and contextual rules to specialize that pattern for each instantiation.

Here is a (not very good) example:

```
ScreenManager:
    Screen:
        id: one
    Screen:
        id: two

<Screen>:
    id: screen
    BoxLayout:
        orientation: "vertical"
        id: screen-layout
        Label:
            id: banner
            size_hint: 1,None
            height: dp(50)
        Button:
            id: button1
            screen: screen

<<Screen#one>>:
    name: "un"

<<Screen#two>>:
    name: "deux"

<<Screen#one Label#banner>>:
    text: "Screen 1"

<<Screen#two Label#banner>>:
    text: "Screen 2"

<<Screen#one Button#button1>>:
    text: "To Screen 2"
    on_release:
        root.screen.manager.transition.direction = "left"
        root.screen.manager.current = "deux"

<<Screen#two Button#button1>>:
    text: "To Screen 1"
    on_release:
        root.screen.manager.transition.direction = "right"
        root.screen.manager.current = "un"
```

### CODE REVIEW

**Comment by tshirtman** [comment]
Wow, needs to test this, but i like the idea! :)

**Comment by denys-duchier** [comment]
It is now possible to nest contextual rules.  A nested rule inherits as a prefix the selectors of those it is nested in.  Thus,  the contextual rules of the previous example can now also be written as follows:

```
<<Screen#one>>:
    name: "un"
    <<Label#banner>>:
        text: "Screen 1"
    <<Button#button1>>:
        text: "To Screen 2"
        on_release:
            root.screen.manager.transition.direction = "left"
            root.screen.manager.current = "deux"

<<Screen#two>>:
    name: "deux"
    <<Label#banner>>:
        text: "Screen 2"
    <<Button#button1>>:
        text: "To Screen 1"
        on_release:
            root.screen.manager.transition.direction = "right"
            root.screen.manager.current = "un"
```

**Comment by dessant** [comment]
@tito, are you ok with merging?

**Comment by denys-duchier** [comment]
hem guys, I was seeking **feedback** on this idea. I didn't think of it as ready for merging.  if you like the idea, then I'll go the extra mile to make it ready for merge. note that, when contextual rules are present in the app, caching is automatically turned off.  I have not measured how much of an impact this may have on performance.

**Comment by tito** [comment]
Don't merge @dessant ^^. Theses implying new notion that need thinking first.

Initially, that's something i wanted to target as well, this is why the language have internally selectors for "cls", "id" in addition to the most used class-matching. 
But there is a lot of issues when i tried to go on this road that i simply stopped to work on it, like:
- saving all the callback to unbind them at some point
- ability to reparse/match the whole tree to unapply/reapply new rule
- children!! Some widget don't work with one, or multiple. Any changes to widgets can just be very bad as none of us design a widget to allow changes of the kv rules.

I guess this would be nice to have, if it's currently limited to properties changes.

The syntax could be plug on the current one, there is no need to create a second <<>>.

From now i'll try to think about it and review your initial code. Thanks a LOT of this :)

**Comment by denys-duchier** [comment]
of course, the only reason for <<>> was to **not** interfere with the existing framework, precisely because this was a speculative extension.  I would be glad to get your input and make whatever modification would be beneficial.

**Comment by tito** [comment]
Good initial idea, but the latest feedback wasn't enough to continue the discussion. And the PR itself cannot be merged. Anybody that have an interest can try to revive it!

**Pull request closed without merging**
