### PR TITLE
refactor: moved lang.py into its own module

### PR DESCRIPTION
**Pull request by Gagaro**
Please see discussion there: https://groups.google.com/forum/?hl=fr#!topic/kivy-dev/AN2rmkW1mc0

I moved and split lang.py into its own module. There was part of builder logic in the middle of the parser one, so even if this PR is not merge this should maybe be addressed.

### CODE REVIEW

**Comment by matham** [comment]
The main issue currently is that I cannot tell whether you just copy pasted or also made changes and what they are. Also, this way we lose all git history/blame. Can you do it in a slightly different way as described here: http://stackoverflow.com/a/33992444 ? 

Create the lang dir. Then do `git cp lang.py lang/__init__.py`, `git cp lang.py lang/builder.py`, and `git mv lang.py lang/parser.py`. And commit everything.

Then just delete what needs to be deleted without adding anything and commit. And finally add whatever fixes are required, including e.g. the test fix.

This will make it easier for us to see what changed

**Comment by Gagaro** [comment]
Indeed, I'll do this.

**Comment by Gagaro** [comment]
I couldn't reproduce the bug in travis, do you have any idea what's this could be about?

My output:

```bash
$ python autobuild.py silenced=yes                                                                                                                                 [kivy]gagaro@gagaro-Latitude-E6510
[INFO   ] [Logger      ] Record log in /home/gagaro/.kivy/logs/kivy_16-02-15_9.txt
[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2]
[INFO   ] [Factory     ] 179 symbols loaded
[INFO   ] [OSC         ] using <multiprocessing> for socket
[CRITICAL] [App         ] Unable to get a Window, abort.
 Exception SystemExit: 1 in 'kivy.properties.dpi2px' ignored
[CRITICAL] [App         ] Unable to get a Window, abort.
 Exception SystemExit: 1 in 'kivy.properties.dpi2px' ignored
Auto-generation finished
```

**Comment by dessant** [comment]
This is the relevant part:
https://travis-ci.org/kivy/kivy/jobs/109315880#L2633
```python
   File "/home/travis/build/kivy/kivy/kivy/factory.py", line 139, in __getattr__

     module = __import__(name=item['module'], fromlist='.')

 ImportError: No module named 'kivy.lang.'
```

**Comment by dessant** [comment]
You'll also have to append `kivy.lang` here:
https://github.com/kivy/kivy/blob/master/setup.py#L944

**Comment by dessant** [comment]
And this:
https://github.com/matham/kivy/blob/a80163689a5070cfbc77ac40d239837039018321/kivy/factory_registers.py#L26

**Comment by Gagaro** [comment]
All green, thanks :+1: .

**Comment by matham** [comment]
Great :100:

**Comment by dessant** [comment]
@thopiekar, in case it affects the ppa scripts, lang.py was refactored into a sub package. :dancer:

**Comment by thopiekar** [comment]
What is kivy.lang actually? Something that should go to kivy-tools?

**Comment by dessant** [comment]
It is the belly button of kivy, kv parsing, etc.

**Comment by dessant** [comment]
@thopiekar, maybe I should stop comparing kivy modules to body parts, or a belly button is not that important for everyone :grinning:, so kivy.lang, if not the heart, but is at least the lungs of kivy. :stuck_out_tongue_winking_eye:

**Comment by thopiekar** [comment]
I moved it now to kivy-tools. In case too much people miss it to be installed by default we can move it back to python*-kivy. This might break the packages, but this is the idea of daily PPA's :smile:

**Comment by dessant** [comment]
@thopiekar, ok, let's call kivy.lang the head of the kivy framework. We need heads, always. :joy:

**Comment by thopiekar** [comment]
Oh, no, just have to revert everything again :disappointed:

**Comment by dessant** [comment]
Sorry, i've realized by now that a belly button is mostly useless, i should have started with the head.

**Comment by akshayaurora** [comment]
what's in a head?  headless servers are all the rage now a days :p

**Comment by dessant** [comment]
I guess there is no winning for me with this analogy. :stuck_out_tongue:

**Comment by mmiuttff** [comment]
hi i need halp 
myapp.kv not work wht Myapp.py



_________
Screenshot_٢٠٢٤٠٨٢٣_٢٢٠٦٠٧_RVNC Viewer
Screenshot_٢٠٢٤٠٨٢٣_١٩٢١٢٣_RVNC Viewer
Screenshot_٢٠٢٤٠٨٢٣_١٩٢١٠٧_RVNC Viewer
Screenshot_٢٠٢٤٠٨٢٣_١٨٥٦٤٣_RVNC Viewer
Screenshot_٢٠٢٤٠٨٢٣_١٨٥٥٢٩_RVNC Viewer
Screenshot_٢٠٢٤٠٨٢٣_١٧٢٩٤٠_RVNC Viewer
Screenshot_٢٠٢٤٠٨٢٣_١٧٢٨٣٨_RVNC Viewer

**Pull request merged**
