### PR TITLE
ScrollView: make sure import does not load a window.

### PR DESCRIPTION
**Pull request by akshayaurora**

### CODE REVIEW

**Comment by dessant** [comment]
@akshayaurora, looks great. :dancer: 
It also fixes https://github.com/kivy/kivy/issues/4232.
I'll open a separate issue for the config issue we discussed.

**Comment by kived** [comment]
Seems like it would be better to fix the root problem - that importing Window creates a window.

**Comment by dessant** [comment]
There must be an issue opened about agressive kivy imports.

**Comment by dessant** [comment]
This was also one of them: https://github.com/kivy/kivy/issues/2480
But i also remember a general one.

**Pull request merged**
