### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -S ./doc/sources/changelog.rst -L als,ba,childrens,childs,co-ordinate,co-ordinates,datas,enew,everytime,inout,iself,quitted,tesselate,tesselated,tesselator,ths`

### CODE REVIEW

**Comment by luzpaz** [comment]
Rebased

**Comment by misl6** [comment]
Hi @luzpaz!
Can you please rebase on top of latest master and check if all the automated tests are ✅  ?

**Comment by luzpaz** [comment]
Sure. Rebased. Waiting for tests to complete.

**Review by misl6 — APPROVED** [review]
LGTM. Thank you!

**Pull request merged**
