### PR TITLE
new MasterSlave class added

### PR DESCRIPTION
**Pull request by debeshm**
Hope this new class will be beneficial for kivy application developers in a wide variety of ideas.
The usage of this class is in its documantation

### CODE REVIEW

**Comment by matham** [comment]
This probably belongs in kivy-garden rather than in kivy directly.

**Comment by debeshm** [comment]
matham : thanks for the info

how am I able to know??

**Comment by matham** [comment]
See http://kivy-garden.github.io/

**Comment by tshirtman** [comment]
Also, it seems remotely similar to garden.magnet (unless i'm missing the point)

**Comment by debeshm** [comment]
tshirtman: magnet is like a container but MasterSlave is a normal class which can make a widget follow another widget or follow opposite to another widget at a slower or faster rate

**Comment by debeshm** [comment]
it can be used in many applications or games....and it does not only follows animation but any type of movement...may be due to dragging by user

**Comment by tshirtman** [comment]
Ok, I understand better, no worries.

**Comment by debeshm** [comment]
so is this contribution suitable here or is it suitable for kivy-garden?

**Comment by tshirtman** [comment]
I think it's better in a garden, it's not really a widget, and not a common use case for kivy applications.

**Comment by debeshm** [comment]
ok..all ri8
Thanks....
now I need to know about garden as I am not experienced with it

**Comment by tshirtman** [comment]
The link @matham gave should give you all info, but please ask if you have any question :).

**Comment by debeshm** [comment]
sure

**Comment by akshayaurora** [comment]
closed for garden.

**Pull request closed without merging**
