### PR TITLE
Added scale w.r.t origin property

### PR DESCRIPTION
**Pull request by rastogiachyut**
Added scale(issue #2693 ) with respect to origin property, similarly to how it was done in rotate. The set_scale method coresponds to compute method in rotate.

### CODE REVIEW

**Comment by rastogiachyut** [comment]
two files changed in one commit because if I did it in two there would have been a state in between where the code would be broken.

**Comment by rastogiachyut** [comment]
two files changed in one commit because if I did it in two there would have been a state in between where the code would be broken.

**Comment by inclement** [comment]
Looks good to me, thanks! I've also added a new example demonstrating this feature.

**Comment by rastogiachyut** [comment]
Sorry for  #3070, should have closed that one myself.

**Pull request merged**
