### PR TITLE
Add MultiForm demo/tutorial

### PR DESCRIPTION
**Pull request by KeyWeeUsr**
Similar to #4442 feature request, but this one is about one app with multiple window-like widgets. Around ~200lines, but could be probably shorter.

Except for the obvious, I mentioned there:

* traversing parent-children tree from bottom (from root it's just annoying, hungry and sometimes didn't work for me, to I excluded it)
* post_initialization (because `self.parent` is `None` in `__init__`)
* working with WeakProxies
* hiding widgets
* how properties work

... and so on. I just hope it's not confusing much ^^

image

### CODE REVIEW

**Comment by dessant** [comment]
Wouldn't this be happier as a garden flower?

**Comment by KeyWeeUsr** [comment]
I've thought about it too, but I wasn't sure about it as in garden there is code that you can use (install from it) and just import & go on with your stuff. This is rather demo. I don't mind having it in garden though. :)

**Comment by dessant** [comment]
A part of me would love to see the `examples` folder moved to a `kivy-examples` repo and let it grow more freely, while not clogging the main kivy repository. What do you guys think?

**Comment by KeyWeeUsr** [comment]
Well, I still love how Kivy automatically installs the examples too, so if this doesn't change, it might be a good thing. But then again, if it's a separate repo, it might be less "controlled" and less useful examples might come in. If that means this demo won't be merged because it's on the edge with its usefulness, then rather close it instead of making a new repo that could become congested later.

I may even move it to wiki if that's the case ^^

**Comment by dessant** [comment]
I'm also ok with merging, the code looks ok. My main issue is that we could come up with a large number of examples of this category, and I wouldn't know how to choose and which one to keep. Would you?

**Comment by KeyWeeUsr** [comment]
Most likely I wouldn't be able to choose which one should be included or not (except obvious stuff). However, I'm not sure if this is the way examples should go. It's just a feeling though and I'd like to see the examples grow too. Maybe even in a separate repo. I'm just judging from my own experience as sometimes I'd like to include a lot of stuff and sometimes not so much because making it is just too obvious even without demo.

Don't get me wrong, I'm kind of for both (separate or not) solutions, I'm just unsure what would be the right one.

**Comment by dessant** [comment]
Yeah, these are the hardest decisions. 😋 I regard the examples folder as a place for showing only how to use the kivy api, basic layouts etc, without complex details.

There are already some odd choices, like pyjnius apps: https://github.com/kivy/kivy/tree/master/examples/android. These things could be moved to a kivy-examples repo, where we could import external libs, or show specific ui setups etc. The wiki also has several examples which could belong there.

I'm not sure how the rest of the team feels about this, but I believe some kind of distinction has to be made.

**Comment by dessant** [comment]
@KeyWeeUsr, if not the garden, then this could live in the wiki until some new structure is figured out for examples. I'm hesitating, but I'll close this. 👼

**Pull request closed without merging**
