### PR TITLE
Add TreeView.deselect_node()

### PR DESCRIPTION
**Pull request by KeyWeeUsr**
This solves the issue #3572 but I'm not quite sure if it's a good idea. On the other hand, it could be tweeked a little bit more to `node=None` by default and that way it could prevent crashing an app.

### CODE REVIEW

**Comment by matham** [comment]
I'm not sure I like the idea of simply leaving node to None in a select function implying something about deslecting. Why would it not work to deselect directly? Also, that kind of thing makes sense when touching a node, i.e. one touch selects, the next deselects. But not in underlying api code.

**Comment by KeyWeeUsr** [comment]
It's not about None directly, but it deselects only if there's something other selected if I'm right. I didn't find a deselecting function and I used already working function to deselect, which in the beginning(everything deselected), the variable holding node is equal to None.

Use case would be deselecting everything with clock maybe.

**Comment by matham** [comment]
Right, the problem is with the the implicit behavior that when it's None and there's something selected, it deselects it. This method is called select not toggle so that  behavior would be very unexpected. The method currently on deselects when a new one is selected instead which is expected.

While there isn't a deselect method, there really should be, with the same behavior you're suggesting to deselect the current one if node is None (in that method).

**Comment by KeyWeeUsr** [comment]
Ah, got it! Will look into that soon.

**Comment by matham** [comment]
Just a small comment, I think that method should have a node parameter to be used to delect that node. Only if the node param is None should we deselect the currently selected node.

**Comment by KeyWeeUsr** [comment]
Well, I tried to select multiple nodes with `shift` or `ctrl`, but no succes there, so I guess it's not really possible from user's side. Also `select_node()` always deselects the old node, so that wouldn't work too.

There's is however a possibility to select multiple nodes with passing `is_selected=True`, but this way a user can't deselect by clicking on some other node. A click on the selected node is necessary to "select" it once more and then it deselects. (probably bug anyway)

**Pull request merged**
