### PR TITLE
textinput-filter: comma

### PR DESCRIPTION
**Pull request by picibucor**
textinput-filter accepts commas as separator as well

### CODE REVIEW

**Comment by matham** [comment]
Python doesn't seem to accept a comma:

```py
>>> float('3.5')
3.5
>>> float('3,5')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ValueError: invalid literal for float(): 3,5

```

**Comment by matham** [comment]
If it's a local specific thing, then we would need to make it local dependent in kivy too.

**Comment by picibucor** [comment]
Just one directive, out of many:
http://www.iec.ch/standardsdev/resources/draftingpublications/writing_editing/directives/numbers.htm

**Comment by picibucor** [comment]
Check the standards of IEC, for example:
http://www.iec.ch/standardsdev/resources/draftingpublications/writing_editing/directives/numbers.htm

**Comment by picibucor** [comment]
sorry, missclicked

**Comment by dessant** [comment]
http://babel.pocoo.org/ could be used to get the localization data.

**Comment by picibucor** [comment]
@dessant : Thank you, Babel seems to be very useful.
According to my experiences the input_filter: float  filters out everything what not number '[^0-9]' or  the first dot is.
Do I understand it right:
If I want to use Babel to convert the "local" input-text (comma instead of dot) into a python-accepted format (dot) I cannot use the "input_filter: float" option in the kv-file.

**Comment by dessant** [comment]
@picibucor you could pass a function to input_filter that filters out everything that is not a dot, comma or number, the sanitized string would be passed to babel and you would just return the localized string from your function.

**Comment by picibucor** [comment]
Do you mean so:
TextInput:
    input_filter:  [^0-9.,-]
?

**Comment by akshayaurora** [comment]
Replaced by https://github.com/kivy/kivy/pull/3745, where we aim reuse internal python checking int/float to check if the value is valid.

**Pull request closed without merging**
