### PR TITLE
Add clipboard example

### PR DESCRIPTION
**Pull request by KeyWeeUsr**
(...and fix ugly import in docs.)

Example that makes use of clipboard for creating widgets e.g. for pasting values from spreadsheet.

### CODE REVIEW

**Comment by rafalo1333** [comment]
@KeyWeeUsr actually removing this ugly import would KV from docs crashing ;) Clipboard is not uix class and its not available in KV namespace, so without this import the code would not run.

**Comment by KeyWeeUsr** [comment]
@rafalo1333 sure:

```
from kivy.lang import Builder
from kivy.base import runTouchApp
from kivy.uix.boxlayout import BoxLayout
Builder.load_string('''
#:import Clipboard kivy.core.clipboard.Clipboard
<Test>:
    Button:
        on_release:
            self.text = Clipboard.paste()
            Clipboard.copy('Data')
''')
class Test(BoxLayout): pass
runTouchApp(Test())
```

**Comment by rafalo1333** [comment]
Its working when Clipboard is imported. When you remove it, after button release app crashes with the obvious error: 

```
  File "<string>", line 5, in <module>
 NameError: name 'Clipboard' is not defined
```

**Comment by KeyWeeUsr** [comment]
That's why I put the python import from `on_release` to the top and made it kv import. Of course if you remove it completely it'll crash. Did you see the diff btw?

**Pull request merged**
