### PR TITLE
Fix for pep8 errors

### PR DESCRIPTION
**Pull request by saqib1707**
Did pep8 fixes.

### CODE REVIEW

**Comment by dessant** [comment]
Thanks @saqib1707! There are some minor fixes that need to be made (i'll follow up with a commit), but overall it's a solid contribution.

**Comment by udiboy1209** [comment]
@dessant  I found [this line](https://github.com/kivy/kivy/pull/4815/files#diff-5f05a9fe836a8283afe4a523b2038a32R216) which will add unnecessary tabs to the log output. 

Apart from that, great contribution @saqib1707! thanks!

**Comment by dessant** [comment]
@udiboy1209 nice catch, that was not on my list.

**Comment by phunsukwangdu** [comment]
Great!! i was working on the same issue!! #4814

**Comment by dessant** [comment]
I have added E741 to the ignore list, in some places the `l -> z` replacement made the code harder to understand, like here: https://github.com/kivy/kivy/pull/4815/files#diff-480d2648b9998d693c37b6a52732eff3R610.

**Comment by udiboy1209** [comment]
E741 doesn't concern most monospace fonts because they clearly distinguish between lowercase `l` and uppercase `I`. I also felt it should be ignored :smile:

**Comment by dessant** [comment]
Sigh, github was not expanding the diff for textinput.py and I completely missed it.

@saqib1707, how did this end up in you pr? https://github.com/kivy/kivy/pull/4815/files#diff-f6433d5683536d9ce43c2441a159250eR149

**Comment by saqib1707** [comment]
I dont know how this happened ..But ok let me correct this..

**Comment by saqib1707** [comment]
@dessant should I create a new PR for the textinput.py file since I have pushed it to my kivy repo but it is not appearing here ?

**Comment by dessant** [comment]
@saqib1707, I'm not sure what do you mean by that, your only option is to create a new PR if this was already merged.

**Comment by dessant** [comment]
The textinput.py changes were reverted in https://github.com/kivy/kivy/commit/d7e807998ca9b50e2c4ebb972361668b4ba5e133.

**Pull request merged**
