### PR TITLE
Add Linux AArch64 wheel build support

### PR DESCRIPTION
**Pull request by odidev**
Closes https://github.com/kivy/kivy/issues/7670

Maintainer merge checklist
* [x] Title is descriptive/clear for inclusion in release notes.
* [ ] Applied a `Component: xxx` label.
* [ ] Applied the `api-deprecation` or `api-break` label.
* [ ] Applied the `release-highlight` label to be highlighted in release notes.
* [ ] Added to the milestone version it was merged into.
* [ ] **Unittests** are included in PR.
* [ ] Properly documented, including `versionadded`, `versionchanged` as needed.

### CODE REVIEW

**Comment by misl6** [comment]
Hi @odidev,

I've added the `[build wheel linux]` tag into your PR name, so the CI can build linux wheels.
Feel free to add your optimisation commits, and let me know when you're ready for a review.
Would be nice to get it merged before Kivy 2.1.0 :)

**Comment by matham** [comment]
Sadly, you can't edit the title to make it work, as explained [here](https://github.community/t/when-changing-the-pr-title-github-event-pull-request-title-wont-pick-up-the-new-title/171784). You needed to originally open it with the build command in the title.

**Comment by misl6** [comment]
Yep, reminded it after triggering the re-run ☹️

But, new commits, made to this PR, should be able to trigger the build.

**Comment by matham** [comment]
>But, new commits, made to this PR, should be able to trigger the build.

I'm not sure that the title will be changed though internally. I remember when testing it didn't work 😬

**Comment by misl6** [comment]
> > But, new commits, made to this PR, should be able to trigger the build.
> 
> I'm not sure that the title will be changed though internally. I remember when testing it didn't work 😬

Uhm, I did it recently, multiple times and it worked.
But maybe I was making an improper use of a bug (When a bug is actually a feature 😂 ) .

@odidev Can you try to push a minor commit to see if the CI gives us a ✅ ?

Also, there's a specific reason to target `ubuntu-18.04` ?

**Comment by matham** [comment]
I changed the ubuntu version and it did make the wheels! Although I didn't change it everywhere, although probably should.

**Review by matham — APPROVED** [review]

**Pull request merged**
