### PR TITLE
Add canvas argument to FloatLayout.add_widget

### PR DESCRIPTION
**Pull request by LogicalDash**
It's another PR just like #5715, this time for FloatLayout. It lets you pass the "canvas" argument to the add_widget method.

Not sure how I missed that. Sorry!

### CODE REVIEW

**Comment by LogicalDash** [comment]
Appveyor says I cancelled the build but I totally didn't.

**Comment by Zen-CODE** [comment]
:-) Checking it out now....

**Comment by tshirtman** [comment]
Yes, we did because all the builds where failing and it was taking hours to get to the potential fix, sorry about that. restarting it.

**Comment by Zen-CODE** [comment]
Thanks :-)

**Comment by LogicalDash** [comment]
Thank you, too!

**Pull request merged**
