### PR TITLE
feat: add VOIP with permission verification to Kivy

### PR DESCRIPTION
**Pull request by SanquezH**
- Integrate VOIP functionality for developers
- Includes support for SSL/TLS to ensure encrypted communication
- Implement permission verification for microphone access

Full project example: https://github.com/SanquezH/Kivy-VOIP

Maintainer merge checklist
* [ ] Title is descriptive/clear for inclusion in release notes.
* [ ] Applied a `Component: xxx` label.
* [ ] Applied the `api-deprecation` or `api-break` label.
* [ ] Applied the `release-highlight` label to be highlighted in release notes.
* [ ] Added to the milestone version it was merged into.
* [ ] **Unittests** are included in PR.
* [ ] Properly documented, including `versionadded`, `versionchanged` as needed.

### CODE REVIEW

**Comment by kengoon** [comment]
@SanquezH nice work here, really love the feature. I've already stared your original project. But I must point out that this repository might be the wrong place to push this code because Kivy is just focused on the core interactions and user interface of an app. You might want to move this to pyjnius or kvdroid repository due to the feature you implemented does not have anything to do with Kivy directly.

**Comment by SanquezH** [comment]
@kengoon Thank you for the reply, this is my first time contributing on GitHub. You are right, although this project supports kivy on the backend, it does not contribute to anything graphical user interface wise. I shall fork and then pull the final commit of this code to pyjnuis instead.

**Comment by kuzeyron** [comment]
I personally think [Plyer](https://github.com/kivy/plyer) is a better place for this implementation.

**Comment by misl6** [comment]
Closed as now the PR has been moved to https://github.com/kivy/plyer/pull/823

**Pull request closed without merging**
