### PR TITLE
Docs review before release 2.1.0

### PR DESCRIPTION
**Pull request by misl6**
Maintainer merge checklist
* [ ] Title is descriptive/clear for inclusion in release notes.
* [x] Applied a `Component: xxx` label.
* [ ] Applied the `api-deprecation` or `api-break` label.
* [ ] Applied the `release-highlight` label to be highlighted in release notes.
* [x] Added to the milestone version it was merged into.
* [ ] **Unittests** are included in PR.
* [ ] Properly documented, including `versionadded`, `versionchanged` as needed.

### CODE REVIEW

**Review by tshirtman — APPROVED** [review]
LGTM :)

**Comment by misl6** [comment]
Ok, should be ready for a review. Maybe I'm missing something, especially on the Windows side.

**Review by tshirtman — APPROVED** [review]
I don't know if there is more to do (well, there is *always* more to do), but i approve of these changes :)

**Comment by misl6** [comment]
> I don't know if there is more to do (well, there is _always_ more to do), but i approve of these changes :)

That's why 48 hours days are needed :)

**Pull request merged**
