### PR TITLE
proposed fix for #4353 DropDown.max_height not working

### PR DESCRIPTION
**Pull request by tshirtman**

### CODE REVIEW

**Comment by rafalo1333** [comment]
Good work, @tshirtman. After the fix, `max_height` works, but the new problem appeared. When the window height is very small (with max_height set), or when it's height is smaller than container's `minimum_height` (when `max_height` is None) the dropdown refuses to open or just disappears (f.e. when we resize the window to be small in height). This behavior is easy to see with Spinner, but also with module example. I tried to search for a fix, but with no success. The bug is somewhere in _reposition, for sure.

**Comment by tshirtman** [comment]
hm, i though i had tested that, but will look again later today, hopefully.

**Comment by tshirtman** [comment]
Should be ok now :)

**Comment by rafalo1333** [comment]
Great work @tshirtman , works like a charm! Ready to merge.

**Comment by tshirtman** [comment]
great, merging then :)

**Pull request merged**
