### PR TITLE
Add default font function

### PR DESCRIPTION
**Pull request by mixedCase**
This replicates the functionality from PR kivy/kivy#2412 but makes it
mergeable with current master.

It probably needs documentation, not sure where to add it. Thoughts?

### CODE REVIEW

**Comment by rafalo1333** [comment]
@mixedCase good one, but in set_default_font I would use kivy.resources.resource_find() method, instead of simply assigning the value.

**Comment by dessant** [comment]
@rafalo1333, `resource_find` is used internally for resolving `font_name`.

**Comment by dessant** [comment]
I think the previous pr was held back because it didn't properly fix the issue. The correct solution would also let us specify a default font *before* `LabelBase.register` is called [here](https://github.com/kivy/kivy/blob/c779254148c3e45d0fd2525e9f0b165e12f7bec0/kivy/core/text/__init__.py#L778), and unregister the current default font if set_default_font is called during runtime.

In any case, DEFAULT_FONT should not be a string, but a dict so we can properly pass values to `register`.
For the current default, it would look like this (`italic`, `bold` and `bolditalic` are optional):

```python
DEFAULT_FONT = {'name': 'Roboto',
                'regular': 'Roboto-Regular',
                'italic': 'Roboto-Italic',
                'bold': 'Roboto-Bold',
                'bolditalic': 'Roboto-BoldItalic'}
```

**Comment by mixedCase** [comment]
Truth be told I wasn't the one originally interested in adding this functionality and I thought the problem was just getting the previous PR ready to merge. Therefore I'll be closing this PR, sorry.

**Pull request closed without merging**
