### PR TITLE
VLC mediaplayer integration example  for android

### PR DESCRIPTION
**Pull request by ibobalo**
p4a vlc recipe required

### CODE REVIEW

**Comment by dessant** [comment]
@ibobalo, great work! Please make sure that the builds are not failing https://travis-ci.org/kivy/kivy/builds/87837450.

Those two commits from tshirtman should be removed, they are not in master.

**Comment by ibobalo** [comment]
sorry. fixed (the wrond merge reverted). try again pls

**Comment by dessant** [comment]
@ibobalo have you pushed the change to your master? It does not show up here.

**Comment by ibobalo** [comment]
actually pushed to master-fixed. then the master fixed renamed to master. now i see github nut support this. pity. i'l cancel this pull request and will make new

**Comment by ivlevdenis** [comment]
Thank you, you've done half my job of writing wrappers for omxplayer :+1:

**Pull request closed without merging**
