### PR TITLE
First stab at a theme manager.

### PR DESCRIPTION
**Pull request by buchuki**
It seems to work pretty good. We may try to improve it by writing a
complete theme for Kivy. Maybe something from Android or iOS or Redmond.

This is based on Proposal 2 from #691. My next step will be to start building a fully functional theme and tweak this pull request as I find errors. Any feedback would be great!

### CODE REVIEW

**Comment by curaloucura** [comment]
Hello everyone. I wonder if this idea for theming is still on or is it going to a different direction? Tried to find something out on the web but everything looks quite old. This PR is almost 1 year old already  :)

**Comment by buchuki** [comment]
I haven't heard any recent discussion on how this could be done, but I'm pretty sure the code in this PR could be used without having to merge it into the Kivy codebase.

**Comment by curaloucura** [comment]
Thank you buchuki. I actually ran into an exception using it against the most recent 1.9dev Kivy version, Seems that the properties overriding is somehow not working and I always got an exception when applying a theme. I can't reproduce it right now since I'm not in the computer with Kivy configured, but I ended up using multiple inheritance in my python and KV files, but I was curious if a more definite has evolved.

**Comment by tito** [comment]
As the PR is broken, the idea is still cool and respectable. The implementation is as well. Please, if someone is interested, move it as a kivy-garden extension!

**Comment by buchuki** [comment]
If someone wants to take over the pull request, you're welcome to it. if it doesn't happen, I'll try to find time to create the extension tito mentioned, but for me "finding time" means sometime in 2016 if I'm lucky.

**Pull request closed without merging**
