### PR TITLE
Add support for RTL language due to the issue #7704

### PR DESCRIPTION
**Pull request by bambier**
Maintainer merge checklist
* [ ] Title is descriptive/clear for inclusion in release notes.
* [ ] Applied a `Component: xxx` label.
* [ ] Applied the `api-deprecation` or `api-break` label.
* [ ] Applied the `release-highlight` label to be highlighted in release notes.
* [ ] Added to the milestone version it was merged into.
* [ ] **Unittests** are included in PR.
* [ ] Properly documented, including `versionadded`, `versionchanged` as needed.

## Explanation of problem:
As I [described](https://github.com/kivy/kivy/issues/7704#issuecomment-1579971901) in #7704 Persian not supported very well when we use 
```
font_direction: "rtl"
font_script_name: "Arab"
```
I changed the text getting method to fix this problem.

In other hand I added [Vaziri](https://rastikerdar.github.io/vazirmatn/en) font which supports both Latin (Roboto) and Arabic (Vaziri) language by defualt that users can use them if they want.

Also changed requirements that needed for `python-bidi` and `arabic-reshaper`.

### CODE REVIEW

**Comment by p0lygun** [comment]
i am not sure about adding dependencies to the project :thinking: , maybe @misl6 can share his thoughts ?

**Comment by misl6** [comment]
Hi @bambier !

Enhancing support for more languages and scripts is something we are working on, and is really important for us.

However, new built-in fonts in our collection do not look like a good idea, as it will increase the package size for everyone.
(I do not even think that is really a good idea to ship fonts for latin languages, but I guess we can only remove them during a major version release (e.g. `3.x.x`) : https://github.com/kivy/kivy/tree/master/kivy/data/fonts)

Instead, I think we should add a section to our documentation (and you're encouraged to do so) that explains how to access system fonts and suggestions about free fonts to support specific languages or scripts.

**About the additional dependencies:**
Aren't [font_direction](https://kivy.org/doc/stable/api-kivy.uix.label.html#kivy.uix.label.Label.font_direction) and [font_script_name](https://kivy.org/doc/stable/api-kivy.uix.label.html#kivy.uix.label.Label.font_script_name) not enough for your use case?
If not, can you explain why?

**Comment by bambier** [comment]
> Hi @bambier !
> 
> Enhancing support for more languages and scripts is something we are working on, and is really important for us.
> 
> However, new built-in fonts in our collection do not look like a good idea, as it will increase the package size for everyone. (I do not even think that is really a good idea to ship fonts for latin languages, but I guess we can only remove them during a major version release (e.g. `3.x.x`) : https://github.com/kivy/kivy/tree/master/kivy/data/fonts)
> 
> Instead, I think we should add a section to our documentation (and you're encouraged to do so) that explains how to access system fonts and suggestions about free fonts to support specific languages or scripts.
> 
> **About the additional dependencies:** Aren't [font_direction](https://kivy.org/doc/stable/api-kivy.uix.label.html#kivy.uix.label.Label.font_direction) and [font_script_name](https://kivy.org/doc/stable/api-kivy.uix.label.html#kivy.uix.label.Label.font_script_name) not enough for your use case? If not, can you explain why?

Hi
As I said earlier in issues (https://github.com/kivy/kivy/issues/7704#issuecomment-1577493312) and (https://github.com/kivy/kivy/issues/7704#issuecomment-1579971901) when we use `font_direction` and `font_script_name` unnecessary margin/paddings affects on text also when we use both RTL and NON-RTL words together we can obviously see that those are broken and looks weird but with these libraries words look good.

About fonts I dont think using only Latin supporting fonts is good idea, isn't it better use font that supports every language or just use phone internal font system (or something similar! All android phone has their own fonts in side them so it makes app lighter)

**Comment by misl6** [comment]
> About fonts, I dont think using only Latin supporting fonts is a good idea. Isn't it better to use font that supports every language (Vaziri font supports both Latin and Arabic characters so we dont need Roboto font and we can delete them) or just use phone internal font system (or something similar! All android phone has their own fonts on them, so they make the app lighter)

As I said in my [previous comment](https://github.com/kivy/kivy/pull/8367#issuecomment-1742078174), accessing system fonts looks like a good idea. (and avoid us to include new fonts).
Deleting/replacing fonts, is not possible, at least not with a major release, cause it may break apps appearance. However, better to discuss that topic separately. (We can find a workaround)

From what I can see, here the main issue is that we're forcing the text direction for all the string, and not only for specific chunks (as it should be).

Can you confirm that the reshaper is not needed if `font_script_name` is set to `Arab` and the string does not mix rtl and non-rtl text, as our implementation with `harfbuzz` already provides a proper handling?

**Pull request closed without merging**
