### PR TITLE
Add screenshots for widgets

### PR DESCRIPTION
**Pull request by KeyWeeUsr**
This PR adds screenshots for dynamic widgets i.e. the widgets provide a specific movement and pure `.png`/`.jpg` isn't enough. PR also completes screenshots for static widgets that may be neccessary to see(design):

static:
- label(markup)
- treeview(how it looks)

dynamic:
- carousel
- dropdown
- scatter
- pagelayout
- stencilview
- screenmanager(all transitions ordered as in docs)

ref #3554 ?

### CODE REVIEW

**Comment by dessant** [comment]
Nice job @KeyWeeUsr, I like that the images have a compact size and do not contain unnecessary elements.

**Comment by dessant** [comment]
@KeyWeeUsr, the images do not appear on the built doc pages.

**Comment by KeyWeeUsr** [comment]
image
 I see them there O.o

**Comment by dessant** [comment]
Pff, this is odd, I was browsing the same page and this is what i've seen, but now it works.
capture

**Comment by dessant** [comment]
We should also ensure that the image is contained in the parent div and does not cover other elements.

**Comment by KeyWeeUsr** [comment]
I was thinking exactly the same when I saw [ColorPicker](https://kivy.org/docs/api-kivy.uix.colorpicker.html) mainly because the "code" div keeps whole width of a parent and images are placed right above that div. If I make the images smaller or something it won't fix the issue. The image is already in the parent div, the problem is that the other elements are too. I'm not really sure with this, but I can't place images into paragraphs, can I?
image
The necessary change should maybe target the default template for docs i.e. there should be a place for an image and hopefully image of consistent shape if it's not something like ActionBar.

**Pull request merged**
