### PR TITLE
Make cc0 video smaller

### PR DESCRIPTION
**Pull request by KeyWeeUsr**
The video is now 1.65MB (previously 4.36MB), with a smaller resolution + bitrate changed to 2000kbps. Also I corrected the timing of subtitles which seemed a bit off as the video is ~7sec long.

Changing the video to a lower bitrate might help with the size more and would probably kick even under 1MB, but the resolution is really small now and the frames are changing to pixelated something with compression artifacts. I'm not sure if I should try to push it more and make the quality worse.

### CODE REVIEW

**Comment by dessant** [comment]
If we have only one video file, it might be ok to keep it as is, this new version is really low quality. I'm also ok witch merging if others want it, it just seems like it would offer a not so flashy experience in a video playback example.

**Comment by FeralBytes** [comment]
Would be nice if the video had a disclaimer like "Low Resolution Video Test".

**Comment by dessant** [comment]
Yeah, but that wouldn't make the experience better.

**Comment by dessant** [comment]
Let's close this. We could use the original mp4 file (2.2MB) when the ffpyplayer recipe for android gets merged.

https://videos.pexels.com/videos/time-lapse-video-of-tall-buildings-894

**Pull request closed without merging**
