### PR TITLE
allow NumericProperties to accept type double

### PR DESCRIPTION
**Pull request by sirpercival**
There's no reason not to, is there?

### CODE REVIEW

**Comment by inclement** [comment]
Python's numeric types are int, float, long and complex - floats are probably implemented with doubles internally. Other than that, double isn't a defined variable and (unless I miss something) this code won't compile.

I've never thought about it but maybe we should accept complex numbers...though the lack of ordering etc. might break things, it's not necessarily a natural extension.

**Comment by sirpercival** [comment]
aha - i was using double in cython and i forgot it wasn't a native python type. the actual type ends up being numpy.float64. what about accepting numpy numeric types?

**Comment by inclement** [comment]
It would be nice to accept numpy's numeric types, but we can't rely on the numpy import, and even then it's kind of arbitrary to stop there. We could try to convert anyting unrecognised with float() or similar, but then some things won't end up being what people expect. Maybe this should be considered a doc issue, as I remember the error about it is a bit unclear.

**Comment by sirpercival** [comment]
what about having a compile option to allow numpy types? in my case it seems so far to be ok to convert everything to float, but i'm wondering if there's a situation where it would be problematic.

**Comment by matham** [comment]
I don't think we should make special exceptions for numpy because it's not a python native type. On the other hand, I fail to see why we check if it's a numeric type. Instead we should just check if it's a list/string and do the conversion, otherwise just store the original value. That's how duck typing works anyway. So I'd be in favor of removing the is int etc check.

**Pull request closed without merging**
