### PR TITLE
addition of colour example. 

### PR DESCRIPTION
**Pull request by phunsukwangdu**
The new PR has following changes(reference to closed pr #4790 ):-
-removed layout example
-appropriate naming of folders
-appropriate placing of the example(examples/color_format/main.py )
-rechecked pep8 errors(only on .py file )

### CODE REVIEW

**Comment by kiok46** [comment]
PR looks good but I agree to @Zen-CODE 's point.
`Perhaps the example/widgets/colorpicker.py is a good place to put this? It already shows how colors can be represented in multiple ways, although the way it presents is obscure. Perhaps you could refine that, and clarify the representation in different formats?`

@phunsukwangdu good job +1, could you add the kv stuff from colorusage.kv to the main.py itself, using `Builder.load_string()`?

**Comment by phunsukwangdu** [comment]
I will make the following changes  :) 
-I will merge .kv file in .py  using Builder.load_string()
-refinement of app
-appropriate placement of example

**Comment by phunsukwangdu** [comment]
I have made the changes ! and now i feel it is in merge-able state.

**Comment by dessant** [comment]
I'll merge this and follow up with a bit of cleanup, the text is barely readable with this color, and most of the quotes in kv are not needed. Otherwise it's a nice example. 👍 

@phunsukwangdu, I've learned you're a prospective gsoc student, you could take a look at the style issues in the repo, if you run `make style`, all of them will be listed. Fixing them would make for a lovely pull request. 😋

**Comment by dessant** [comment]
Ref https://github.com/kivy/kivy/commit/1c94c9af439ae953d3c20de513e96691f2a09b37.

**Comment by phunsukwangdu** [comment]
Thx a lot!!
I realised my mistakes and would try to minimise them in future. :) :)

**Pull request merged**
