### PR TITLE
Added docs for Kivy Launcher

### PR DESCRIPTION
**Pull request by KeyWeeUsr**
Added documentation to simplify the process of installation p4a for building Kivy Launcher using kivy-stable and kivy-master.

- doc/sources/guide/packaging.rst
    - added launcher file

- doc/sources/guide/launcher.rst
    - new file with documentation

### CODE REVIEW

**Comment by akshayaurora** [comment]
This repeats installation instructions for bulldozer and py4a any reason to reproduce them here rather than just link to them?

**Comment by KeyWeeUsr** [comment]
I guess line 19 in launcher.rst isn't really necessary, I'll remove it. Prerequisities(http://python-for-android.readthedocs.org/en/latest/prerequisites/) of p4a are not updated for newer versions of Ubuntu, so I pasted them, added solution for obsolete ia32-libs and added what I needed to make it run i.e. openjdk. I can still paste the link and edit it though.
On lines 79+ are instructions with modules for Launcher for easier copy&paste. Lines 100+ are exactly for building the Launcher with the right environment.

**Comment by dessant** [comment]
ref https://github.com/kivy/kivy/issues/2706

**Comment by KeyWeeUsr** [comment]
Since the pygame launcher works with the new toolchain, I'll reword it and add into p4a docs directly.

**Pull request closed without merging**
