### PR TITLE
Fix `BoxShadow` shader crashing issue on Adreno GPUs

### PR DESCRIPTION
**Pull request by DexerBR**
As reported by @yunus-ceyhan in this [issue](https://github.com/kivy/python-for-android/issues/2723) . The shader used in the `BoxShadow` graphics instruction may crash on some Adreno GPUs.

The specific cause is still not very clear, however, there are two possibilities:
- Issue in Adreno GPU driver
- Issue in kivy's Shader implementation

The workaround is to check if the alpha channel of the `frag_color` variable is greater than zero. If so, a pure vector can be returned, otherwise, a vector created with texture2D needs to be returned, to avoid crashes.

### As a reference, for future implementations using shaders:

Code that crashes on Adreno GPUs:
```GLSL
void main(void)
{
    vec4 color = vec4(1.0, 0.0, 1.0, 1.0);
    gl_FragColor = color;
}
```

Code that compiles successfully:
```GLSL
void main(void)
{
    vec4 texture = texture2D(texture0, tex_coord0);
    gl_FragColor = texture;
}
```

Workaround:
```GLSL
void main(void)
{
    vec4 texture = texture2D(texture0, tex_coord0);
    vec4 color = vec4(1.0, 0.0, 1.0, 1.0);

     if (frag_color.a > 0.0) {
         gl_FragColor = color;
     } else {
         gl_FragColor = texture;
     }
}
```

<br>

⚠️ Update:

As found by @misl6 , there seems to be a bug in kivy that does not allow a shader initialization/compilation if the fragment shader is not passed as an argument to Fbo during its creation.
If the shader is passed as the initial argument, then crashes will not occur, even using the code below:

```GLSL
void main(void)
{
     vec4 color = vec4(1.0, 0.0, 1.0, 1.0);
     gl_FragColor = color;
}
```

🟢Taking this into account, the recommended for implementations using Fbo and shader is:
```python
fbo = Fbo(size=(width, height), fs=fs_code)
```

❌ Not recommended (may break on Adreno GPUs):
```python
fbo = Fbo(size=(width, height))
fbo.shader.fs = fs_code
```

Maintainer merge checklist
* [x] Title is descriptive/clear for inclusion in release notes.
* [ ] Applied a `Component: xxx` label.
* [ ] Applied the `api-deprecation` or `api-break` label.
* [ ] Applied the `release-highlight` label to be highlighted in release notes.
* [ ] Added to the milestone version it was merged into.
* [ ] **Unittests** are included in PR.
* [ ] Properly documented, including `versionadded`, `versionchanged` as needed.

### CODE REVIEW

**Comment by misl6** [comment]
Maybe this workaround (we have to discuss about the real cause) also fixes: https://github.com/kivy/kivy/issues/8080 ?
@HeaTTheatR can you perform some tests?

**Comment by HeaTTheatR** [comment]
> Maybe this workaround (we have to discuss about the real cause) also fixes: #8080 ? @HeaTTheatR can you perform some tests?

These changes unfortunately do not fix the problem described in https://github.com/kivy/kivy/issues/8080

**Comment by moonpyx** [comment]
Hello, some time ago I had that problem and the solution was very similar to use texture2D, but recently I made a small implementation which I tested in samsung s22 ultra that uses Adreno to define the final color of the fragment shader which worked for me and I share it with you hoping it will be helpful, here it is:

vec4 HackColor(vec4 color){
    vec4 c=color + (texture2D(texture0, tex_coord0)*vec4(vec3(0.0),1.0));
    color.rgb=c.rgb; 
    color.a = color.a*c.a;
    return color;
}
...
gl_FragColor = HackColor(color);

**Comment by Peter-Port** [comment]
I hope this will be a part of "master",soon.
Thanks for your work, especially to:
T-Dynamos
HeaTTheatR
DexerBR
(found these names during my research)

**Comment by RobertFlatt** [comment]
Seeing several users a day with shader related issues, workaround is always KivyMD 1.0.2 Be nice to see these addressed.
There seem to be two mechanisms
- Android crash discussed here
- Desktop BoxShadow related Shader did not link. e.g. https://groups.google.com/g/kivy-users/c/A1Asirs1I60/m/X7eZDj-rAgAJ  
So far nobody will post an issue for this one.....

**Comment by misl6** [comment]
> Seeing several users a day with shader related issues, workaround is always KivyMD 1.0.2 Be nice to see these addressed. There seem to be two mechanisms
> 
> * Android crash discussed here
> * Desktop BoxShadow related Shader did not link. e.g. https://groups.google.com/g/kivy-users/c/A1Asirs1I60/m/X7eZDj-rAgAJ
>   So far nobody will post an issue for this one.....

Unfortunately, the Google Groups issue reporter only posted a screenshot with ~8 lines of logs, which is not enough to have an idea regarding the cause  😔

About Android and Adreno: I'm silently working (and testing on multiple Adreno chips) with @DexerBR to have a fix / workaround that doesn't look hacky and that fixes the root cause of the issue.

From our findings, looks like that `texture2D(texture0, tex_coord0);` returns a `vec4` full of `NaN` values on Adreno chips, at least during the early setup phase.

**Comment by misl6** [comment]
@DexerBR , thank you for helping with tests and updating the PR!

I'm still investigating about the issue, as it seems we had similar tracebacks that comes from similar conditions (Eg: 3DRendering Example), so we will likely create a patch to fix this issue / documenting it

**Review by misl6 — APPROVED** [review]

**Comment by misl6** [comment]
@HeaTTheatR , I'm waiting for the CI to complete, then when merged into master, can you make some tests on your side?

**Comment by HeaTTheatR** [comment]
> @HeaTTheatR , I'm waiting for the CI to complete, then when merged into master, can you make some tests on your side?

Yes, of course!

**Pull request merged**
