### PR TITLE
Make widget kwargs passing higher priority than kv

### LINKED ISSUE #3118: kwargs ignored if property set via kv
````python
import kivy
kivy.require('1.8.1')

from kivy.app import App
from kivy.lang import Builder
from kivy.uix.button import Button

Builder.load_string('''
<Button>:
    text: 'bad'
''')

class TestApp(App):
    def build(self):
        return Button(text='good')

if __name__ == '__main__':
    TestApp().run()
````

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/9367446-kwargs-ignored-if-property-set-via-kv?utm_campaign=plugin&utm_content=tracker%2F42681&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F42681&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by matham**
Fixes #3118.

This is one solution to that issue. I think ideally if the kv rule has rule bindings than kv has higher priority since it'd be overwritten later anyway. But if the rule is a constant (e.g. `val: 55`) or the rule is not a bindable rule (e.g. `val: self.attr`, where `self.attr` is not a kivy property) then I think kv should have lower priority (i.e. `Widget(val=val)` has higher precedence).

This implements it, although in a bit of a hacky way. But it's the best I could come up with given the problem.

Example code:
```py
from kivy.lang import Builder
from kivy.uix.button import Button

Builder.load_string('''
<Button>:
    text: 'bad'
    height: 55
    width: name.width + 55
    x: (name.swamp + 55) if None else 55
    Widget:
        id: name
''')

b = Button(text='good', height=123, width=123, x=123)
print b.text, b.height, b.width, b.x
```
before prints `bad 55 155 55`.
after prints `good 123 155 123`.

### CODE REVIEW

**Comment by matham** [comment]
Needs tests and a bit more docs.

**Comment by matham** [comment]
Added docs and tests.

**Comment by akshayaurora** [comment]
@matham :+1:

**Comment by dessant** [comment]
This causes issues with ScreenManager, the trigger seems to be when `name` is passed to `SP()`, otherwise it does not crash.

```python
from kivy.config import Config
Config.set('modules', 'inspector', '')

from kivy.app import App
from kivy.lang import Builder
from kivy.factory import Factory
from kivy.clock import Clock


kv = """
<SP@Screen>:
    sm: sm
    ScreenManager:
        id: sm
        Screen:
            name: 'one'
        Screen:
            name: 'two'
"""

Builder.load_string(kv)


class Test(Factory.ScreenManager):

    def __init__(self, *args, **kwargs):
        super(Test, self).__init__(*args, **kwargs)
        Clock.schedule_once(self.add_content)

    def add_content(self, *args):
        sp = Factory.SP(name='main')
        sp.sm.current = 'two'
        self.add_widget(sp)


class TestApp(App):
    def build(self):
        return Test()

if __name__ == '__main__':
    TestApp().run()

```

```python
 Traceback (most recent call last):
   File "E:\dev\prs\main\test.py", line 41, in <module>
     TestApp().run()
   File "e:\dev\envs\py34_x86\kivy\kivy\app.py", line 828, in run
     runTouchApp()
   File "e:\dev\envs\py34_x86\kivy\kivy\base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "e:\dev\envs\py34_x86\kivy\kivy\core\window\window_sdl2.py", line 606, in mainloop
     self._mainloop()
   File "e:\dev\envs\py34_x86\kivy\kivy\core\window\window_sdl2.py", line 361, in _mainloop
     EventLoop.idle()
   File "e:\dev\envs\py34_x86\kivy\kivy\base.py", line 327, in idle
     Clock.tick()
   File "e:\dev\envs\py34_x86\kivy\kivy\clock.py", line 483, in tick
     self._process_events()
   File "e:\dev\envs\py34_x86\kivy\kivy\clock.py", line 615, in _process_events
     event.tick(self._last_tick, remove)
   File "e:\dev\envs\py34_x86\kivy\kivy\clock.py", line 374, in tick
     ret = callback(self._dt)
   File "E:\dev\prs\main\test.py", line 32, in add_content
     sp.sm.current = 'two'
   File "kivy\weakproxy.pyx", line 22, in kivy.weakproxy.WeakProxy.__setattr__ (kivy\weakproxy.c:1235)
   File "kivy\properties.pyx", line 408, in kivy.properties.Property.__set__ (kivy\properties.c:5114)
   File "kivy\properties.pyx", line 446, in kivy.properties.Property.set (kivy\properties.c:5876)
   File "kivy\properties.pyx", line 501, in kivy.properties.Property.dispatch (kivy\properties.c:6557)
   File "kivy\_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy\_event.c:13497)
   File "kivy\_event.pyx", line 1130, in kivy._event.EventObservers._dispatch (kivy\_event.c:12696)
   File "e:\dev\envs\py34_x86\kivy\kivy\uix\screenmanager.py", line 916, in on_current
     screen = self.get_screen(value)
   File "e:\dev\envs\py34_x86\kivy\kivy\uix\screenmanager.py", line 944, in get_screen
     raise ScreenManagerException('No Screen with name "%s".' % name)
 kivy.uix.screenmanager.ScreenManagerException: No Screen with name "two".
```

**Comment by matham** [comment]
Fixed by https://github.com/kivy/kivy/pull/3795.

**Pull request merged**
