### PR TITLE
Actually display multitouch emulation if sim set to True.

### PR DESCRIPTION
**Pull request by matham**
It didn't display it when the sim profile was set to True, even though it should have. Instead it never displayed the sim touch.

### CODE REVIEW

**Comment by KeyWeeUsr** [comment]
@matham do you have any simple example/instructions to test it with?

**Comment by matham** [comment]
Yeah, set multitouch on demand in config and then right click in a normal widget vs scatter. Previously it would never show the red dot (but would still emulate it so it'd be invisible), now it does it for scatter only.

**Comment by KeyWeeUsr** [comment]
Reproduced, feel free to merge. I'm trying to create a simple unittest for that. :)

**Comment by KeyWeeUsr** [comment]
I wonder why is it a different behavior for `on_demand` simulator and the default one i.e. why the default one works correctly right after pressing and the `on_demand` only after releasing? Shouldn't they match?

**Comment by matham** [comment]
The default is verrrrry greedy and always puts the dot. With on_demand, at the time of press we don't know whether it'll be a mulittouch sim touch, so we wait until release.

**Pull request merged**
