### PR TITLE
Deprecate the interactive launcher

### PR DESCRIPTION
**Pull request by dessant**

### CODE REVIEW

**Comment by matham** [comment]
Why?

**Comment by dessant** [comment]
@matham, there were discussions on irc about deprecating it for some time.
It is generally buggy and broken, and people seem to think that it should be rewritten rather than patched.

**Comment by akshayaurora** [comment]
This is a good idea, we need to provide a alternative too, though for now just deprecating is necessary. It's unmaintained code. We can simply use twisted manhole that already works wonders for us on kivy-remote-shell.

**Comment by kawing-chiu** [comment]
What is the alternative to interactive launcher? Does kivy support interactive usage in ipython currently?

**Pull request merged**
