### PR TITLE
Add disclaimer to use `RecycleView` instead of `ScrollView` for large datasets

### LINKED ISSUE #8149: ScrollView and RecycleView difference
Hello, could you put a disclaimer on the page with ScrollView that it is not optimized for big data and point to RecycleView (**I spent about 10 hours to figure out why my application in .apk had 4 fps**)
I hope this helps someone

### PR DESCRIPTION
**Pull request by kulothunganug**
Closes #8149

Maintainer merge checklist
* [X] Title is descriptive/clear for inclusion in release notes.
* [x] Applied a `Component: xxx` label.
* [ ] Applied the `api-deprecation` or `api-break` label.
* [ ] Applied the `release-highlight` label to be highlighted in release notes.
* [x] Added to the milestone version it was merged into.
* [ ] **Unittests** are included in PR.
* [ ] Properly documented, including `versionadded`, `versionchanged` as needed.

### CODE REVIEW

**Comment by pythonic64** [comment]
@Kulothungan16 Can you use ":class:\`~kivy.uix.recycleview.RecycleView\`" so that docs can have a hyperlink to `RecyclevView`?

**Comment by misl6** [comment]
Hi @Kulothungan16 !

PEP8 checks are failing (See: https://github.com/kivy/kivy/actions/runs/5276660385/jobs/9621218239?pr=8274), can you please take care of it?

**Comment by Kulothungan16** [comment]
Apologies for neglecting GitHub tests in the pull request. I will ensure better attention in the future.
Thanks for addressing it! :)

**Comment by misl6** [comment]
> Apologies for neglecting GitHub tests in the pull request. I will ensure better attention in the future.
> Thanks for addressing it! :)

CI tests are here to catch this kind of issues, otherwise, it will only act as a non-environmental friendly waste of energy 😅

So, do not worry about that!

**Comment by kulothunganug** [comment]
Hi, I have fixed the PEP8 issue.

**Comment by Julian-O** [comment]
I am not an official reviewer. It looks acceptable to me. I probably would have preferred if the text explained *why* you should use a different class, but not enough to stop the merge.

Can we get this one merged?

**Review by misl6 — APPROVED** [review]
LGTM. Thank you!

**Pull request merged**
