### PR TITLE
Implement ScreenManager.display_screen function

### PR DESCRIPTION
**Pull request by rnixx**
Here's the pull request related to #3126

### CODE REVIEW

**Comment by inclement** [comment]
Sorry for the delay reviewing this. I guess the point is that this should be a better (and more flexible) replacement for switch_to?

It seems good (and we need such a thing), but I think a better solution would be to merge the two functions and have a default parameter option to remove the previous screen. That way the api does not become more cluttered. I'll see what others think.

**Comment by dessant** [comment]
I second that, the new behavior should be integrated in switch_to.

**Comment by rnixx** [comment]
@inclement - the idea behind using a new signature is not to break code depending on the existing behavior, deprecate switch_to in favor of display_page and remove switch_to after a while.

the remove flag is already implemented in display_page

**Comment by rnixx** [comment]
@inclement the motivation behind the new function is documented in #3126

**Comment by rnixx** [comment]
anyone else? how to handle this further? should i simply replace switch_to now?

**Comment by inclement** [comment]
I do think this should be integrated with switch_to. Sorry for not replying earlier, we did discuss this a little on irc and had some disagreement about it - though I don't think anyone preferred the option of adding a new method name.

**Comment by rnixx** [comment]
The related code can be found at https://gist.github.com/rnixx/2aab5e13e17c1582b6dd

**Pull request closed without merging**
