### PR TITLE
Clipboard: fixes blank string being pasted into clipboard when using the default `win32` backend

### LINKED ISSUE #8314: Clipboard (under Windows) fails to copy special symbols (affects for example TextInput)
* Python: 3.10.9
* OS: Windows 10
* Kivy: 2.1.0 & 2.2.1
* Kivy installation method: pip install

The `Clipboard` (at least under Windows) fails to copy strings that have certain symbols, such as 💜 and 💠 and will, if attempting to copy those, result in an empty clipboard instead. Of course text, even with such symbols, should copy into the system clipboard properly. Other processing of such symbols including pasting and reading out work as expected.

**To Reproduce**
```python
from kivy.core.clipboard import Clipboard
text="Hello World"
Clipboard.copy(text)
print(Clipboard.paste()==text)#True

text="Hello 💠 World"
Clipboard.copy(text)
print(Clipboard.paste()==text)#False
```

I'm fairly confident that the exact issue resides within clipboard_winctypes.py in the put method. The `text` variable arrives here well-formed as it should be, but never actually makes it to the system clipboard.
I have verified this by simply replacing the entire put method somewhat lazily with:
```python
import win32clipboard
#...
def put(self, text, mimetype='text/plain'):
	win32clipboard.OpenClipboard()
	win32clipboard.EmptyClipboard()
	win32clipboard.SetClipboardData(win32clipboard.CF_UNICODETEXT, text)
	win32clipboard.CloseClipboard()
```
Which has indeed allowed me to run my Kivy app with text fields that can now copy any of their contents as opposed to just any content without such symbols.

I have not submitted this as a fix and pull request since I'm not aware why exactly the `put` method looks like it does. Someone in the know should be able to make a general fix relatively easily with the provided information though.

### PR DESCRIPTION
**Pull request by p0lygun**
Maintainer merge checklist
* [x] Title is descriptive/clear for inclusion in release notes.
* [x] Applied a `Component: xxx` label.
* [ ] Applied the `api-deprecation` or `api-break` label.
* [ ] Applied the `release-highlight` label to be highlighted in release notes.
* [ ] Added to the milestone version it was merged into.
* [x] **Unittests** are included in PR.
* [ ] Properly documented, including `versionadded`, `versionchanged` as needed.

fixes #8314

### CODE REVIEW

**Comment by pythonic64** [comment]
Can you revert changes on the modules which are not needed to fix the clipboard problem? All modules except:
- kivy/core/clipboard/clipboard_winctypes.py
- kivy/tests/test_clipboard.py

Also, can you remove `random` from the unit test (as test should be deterministic)? You can join the entire `emoji_list`, paste it into clipboard and retrieve it for an assertion test.

**Comment by p0lygun** [comment]
@pythonic64 pls review

**Comment by p0lygun** [comment]
@misl6 , this is completed and can be merged :)

**Review by misl6 — APPROVED** [review]
LGTM, thank you!

Can't test it on Windows, since my old Windows laptop is not reachable ATM, but the CI looks happy with it.

**Comment by misl6** [comment]
Hi @p0lygun ,

I'm sorry to say that our best friend (the CI pipeline), was happy when it should not have been.

After this PR got merged (and reverting this PR commit in a personal branch confirmed that), the CI started to silently fail as explained here: https://github.com/kivy/kivy/issues/8484

Any ideas?

**Comment by p0lygun** [comment]
@misl6 
ohhhh that's bad news.. i'll look into it ASAP thx for the heads up

**Comment by misl6** [comment]
> @misl6 ohhhh that's bad news.. i'll look into it ASAP thx for the heads up

I may have a fix ready (testing now locally), so do not worry!

**Pull request merged**
