### PR TITLE
[WIP] Fixing blurred text

### PR DESCRIPTION
**Pull request by pyfrid**
The following changes has been done:

1) rounding pos and size of layouts children
2) rounding last scrollview translation values after Animation has been finished

Still not sure about Accordion and TreeView.
Blurring of textures as expected appears only during animations.

### CODE REVIEW

**Comment by dessant** [comment]
Related issue: https://github.com/kivy/kivy/issues/2297#issuecomment-158348811.

**Comment by dessant** [comment]
@tito, could you look into this?

**Comment by KeyWeeUsr** [comment]
Seems like a really bad approach to me if it should be the default one mainly because using `Animation` could cause issues. On the other hand, we could perhaps have a Config/Widget option to have integers for `pos` only with a big warning?

**Comment by tito** [comment]
I'm closing this PR.

It won't work before it break the Animation by forcing everything to be an int. The right resolution of the issue is much harder, like every widget should be pixel-aligned but can animate smoothly.

**Pull request closed without merging**
