### PR TITLE
#3253 examples bug fix

### PR DESCRIPTION
**Pull request by SepehrHml**
bugfix for issue #3253 ... wanna start to contribute on kivy 💃

### CODE REVIEW

**Comment by dessant** [comment]
The doc pdf creation fails after the merge.
https://travis-ci.org/kivy/kivy/jobs/133714453

**Comment by SepehrHml** [comment]
😲 i try to find the problem as fast as i can ...

**Comment by SepehrHml** [comment]
ummmm ... i saw logs ... it says : ImportError: No module named 'pygame' ... i never worked with travis but i guess something in the travis config changed that it cant find pygame ... becuase the thing i changed isnt in docs or something :/ dont you think ?

**Comment by dessant** [comment]
The pygame error is normal (see the previous builds), it must be something else.

**Comment by KeyWeeUsr** [comment]
The path is almost the same in [app_video.kv](https://github.com/kivy/kivy/blob/2c67a7b93ff1ce99e6382ea1ec0c849f39fa6b19/examples/kv/app_video.kv), so.. maybe it failed only because of early merge or something, so the test was skipped? Still, makes no sense why it fails [here](https://travis-ci.org/kivy/kivy/jobs/133714453). Maybe an issue with `.mpg` file?

**Comment by dessant** [comment]
@SepehrHml, it was just a coincidence, I've reverted in a branch and the build still fails https://travis-ci.org/kivy/kivy/builds/133858247.

**Pull request merged**
