### PR TITLE
Update clock.py

### PR DESCRIPTION
**Pull request by rastogiachyut**
changed all(4) of the _default_time uses in ClockBase to self.time , to make it faster

### CODE REVIEW

**Comment by rastogiachyut** [comment]
actually I had my reasons mixed up its not faster , actually slightly slower.

**Comment by rastogiachyut** [comment]
this way we have a method we can override if needed , thats why it was recommended I think.

**Comment by matham** [comment]
Weird, but it's not mergeable. If you fix it I'll merge it.

**Comment by rastogiachyut** [comment]
ok, this looks like my clone of kivy time traveled a few commits back?
I pushed and pulled before submitting this.

**Pull request closed without merging**
