### PR TITLE
VLC mediaplayer integration example for android

### PR DESCRIPTION
**Pull request by ibobalo**
p4a vlc recipe required

### CODE REVIEW

**Comment by dessant** [comment]
I see you've made some pep8 commits, the log here contains a complete list of style issues to fix: https://travis-ci.org/kivy/kivy/jobs/88336479.

**Comment by tito** [comment]
I don't feel that this should lend into kivy itself. It would be much better for you to commit in kivy-garden in order to maintain it later.

We're not going to handle any maintenance on that part, it's too specific i guess.

**Comment by akshayaurora** [comment]
@ibobalo nice work!

However I share @tito 's sentiment. This is clearly a lot more than just a example.

The right place for this is inside a garden module, garden is essentially a extensions kind of a aggregate which aggregates user created widgets/modules/extensions.

**Comment by dessant** [comment]
@ibobalo I've created https://github.com/kivy-garden/garden.androidvlc and added you as a maintainer with write access.

Feel free to push your work there, thanks a lot for your work so far. :cherries:

**Pull request closed without merging**
