### PR TITLE
[build wheel] Upgrade more GitHub Actions

### PR DESCRIPTION
**Pull request by cclauss**
Maintainer merge checklist
* [x] Title is descriptive/clear for inclusion in release notes.
* [x] Applied a `Component: xxx` label.
* [ ] Applied the `api-deprecation` or `api-break` label.
* [ ] Applied the `release-highlight` label to be highlighted in release notes.
* [x] Added to the milestone version it was merged into.
* [x] **Unittests** are included in PR.
* [ ] Properly documented, including `versionadded`, `versionchanged` as needed.

A broader application of the changes made in #8117.  Dependabot, Renovate, etc. can automate most of these changes.
* https://github.com/actions/cache/releases
* https://github.com/actions/checkout/releases
* https://github.com/actions/download-artifact/releases
* https://github.com/actions/setup-python/releases
* https://github.com/actions/upload-artifact/releases

### CODE REVIEW

**Comment by misl6** [comment]
Hi @cclauss , I've added `[build wheel]` into title, so we can also test the wheel build, can you force push?

**Comment by cclauss** [comment]
Force pushed https://github.com/kivy/kivy/pull/8120/commits

**Comment by cclauss** [comment]
Several `setup-python` are hard coded to Python `3.9`.  Would it be better to use `3.x` instead so that we are testing, building, etc. on the current Python (currently `3.11`) so that the GitHub Actions catch incompatibilities before users do?

**Comment by misl6** [comment]
> Several `setup-python` are hard coded to Python `3.9`. Would it be better to use `3.x` instead so that we are testing, building, etc. on the current Python (currently `3.11`) so that the GitHub Actions catch incompatibilities before users do?

We needed to force `3.9` in past (https://github.com/kivy/kivy/pull/7674), but there's no reason to stick to it right now.
So, yes, feel free to update our configuration accordingly. (But in a different PR)

**Review by misl6 — APPROVED** [review]
LGTM (And CI is happy). Thank you!

**Pull request merged**
