### PR TITLE
Updated `EventLoop.ensure_window` function to work with lazy initialization of the `Window` class

### PR DESCRIPTION
**Pull request by Samael-TLB**
Reference #8340 

Maintainer merge checklist
* [x] Title is descriptive/clear for inclusion in release notes.
* [ ] Applied a `Component: xxx` label.
* [ ] Applied the `api-deprecation` or `api-break` label.
* [ ] Applied the `release-highlight` label to be highlighted in release notes.
* [ ] Added to the milestone version it was merged into.
* [ ] **Unittests** are included in PR.
* [x] Properly documented, including `versionadded`, `versionchanged` as needed.

### CODE REVIEW

**Comment by p0lygun** [comment]
@Samael-TLB Open a single PR for issue #8340 , as all the PRs target the same issue, 
PRs in question #8355 #8354  #8353 #8352

**Comment by Samael-TLB** [comment]
> @Samael-TLB Open a single PR for issue #8340 , as all the PRs target the same issue, PRs in question #8355 #8354 #8353 #8352

Yes can do that but I just atomized the updates at that time.

**Comment by p0lygun** [comment]
please do it as the other PRs depend on whether the previous PR is merged or not, 
Atomicity should be achieved in commits and PRs should target a feature/fix

**Comment by Samael-TLB** [comment]
> please do it as the other PRs depend on whether the previous PR is merged or not, Atomicity should be achieved in commits and PRs should target a feature/fix

Surely, will do this over the weekend. Also I wanted to connect with you @p0lygun for some discussion, where can we connect, please suggest.

**Comment by p0lygun** [comment]
i am active in kivy's [discord](https://chat.kivy.org/) (username gala_vs), you can also email me if you want at `solankivibhakar82@gmail.com`

**Comment by p0lygun** [comment]
@Samael-TLB any updates?

**Comment by Samael-TLB** [comment]
Merged into one pr by #8376

**Pull request closed without merging**
