### PR TITLE
missing import for tesselator

### PR DESCRIPTION
**Pull request by brentpicasso**
Pyinstaller failed to find the import for Tesselator - added it here

### CODE REVIEW

**Comment by tito** [comment]
Not entirely sure about it. I think pyinstaller must found another way to get it, as already kivy.graphics doesn't contain all the possible class, just the most used and imported by default. Tesselator is not one of them.

How do you import it in your app?

**Comment by brentpicasso** [comment]
Actually, we're not importing it directly, but via the Svg widget.
Pyinstaller seemed to be happy once I made this change.

Here's where we're using the Svg Widget:

https://github.com/autosportlabs/RaceCapture_App/blob/v1.3.7_round_gauge_perf/autosportlabs/racecapture/views/dashboard/widgets/roundgauge.py#L10

-Brent

On Fri, Aug 7, 2015 at 3:03 PM, Mathieu Virbel <notifications@github.com>
wrote:

> Not entirely sure about it. I think pyinstaller must found another way to
> get it, as already kivy.graphics doesn't contain all the possible class,
> just the most used and imported by default. Tesselator is not one of them.
>
> How do you import it in your app?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kivy/kivy/pull/3548#issuecomment-128843029>.
>



-- 
Brent Picasso
*Autosport Labs <http://www.autosportlabs.com>*
*Technology for Race and Street*

**Comment by dessant** [comment]
This should be fixed by https://github.com/kivy/kivy/commit/8bce671be3beff162098bb7162cc922adf558b57.

**Comment by brentpicasso** [comment]
Great, thank you! I see the fix made in the pyinstaller hook, will remember
that.

On Wed, Oct 28, 2015 at 9:08 AM, dessant <notifications@github.com> wrote:

> Closed #3548 <https://github.com/kivy/kivy/pull/3548>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kivy/kivy/pull/3548#event-448184545>.
>



-- 
Brent Picasso
*Autosport Labs <http://www.autosportlabs.com>*
*Technology for Race and Street*

**Pull request closed without merging**
