### PR TITLE
Textinput:  Fixes issues #7165, #7236, #7235

### LINKED ISSUE #7165: TextInput unexpected linebreaks
**Software Versions**
* Python: 3.8.5
* OS: Linux Mint 20 (based on Ubuntu 20.04 LTS)
* Kivy: 2.0.0rc3

**Describe the bug**
If I start entering text (e.g. by holding down "c" key) between letters "a" and "b" in the line "aaaabbbb", then when the text fills all the line, unexpected linebreaks after each letter "b" appears.

**Code and Logs and screenshots**
```python
from kivy.app import App
from kivy.uix.textinput import TextInput

class Sample(App):
    def build(self):
        return TextInput(text="aaabbb")

Sample().run()
```

**Current behavior**
Bug2_current

**Expected behavior**
Bug2_expected

### PR DESCRIPTION
**Pull request by Alspb**
Fixed #7165, #7236, #7235. 

Maintainer merge checklist
* [x] Title is descriptive/clear for inclusion in release notes.
* [x] Applied a `Component: xxx` label.
* [ ] Applied the `api-deprecation` or `api-break` label.
* [ ] Applied the `release-highlight` label to be highlighted in release notes.
* [ ] Added to the milestone version it was merged into.
* [ ] **Unittests** are included in PR.
* [ ] Properly documented, including `versionadded`, `versionchanged` as needed.

### CODE REVIEW

**Comment by DexerBR** [comment]
Coud you take a look into it: #7631 ? Maybe you can help to fix...

**Review by misl6 — DISMISSED** [review]
Nice work!

Issue #7165 looks fixed.
Issue #7236 looks fixed.
Issue #7235 looks fixed.

I left some comments with some improvements that could be made before getting it merged.

**Comment by misl6** [comment]
LGTM.
Can you just please rebase on latest master?

**Comment by Alspb** [comment]
Done

**Review by tshirtman — APPROVED** [review]

**Pull request merged**
