### PR TITLE
Fix #4444 Fixes Nested ScrollView

### LINKED ISSUE #4444: Nested ScrollView touch transformation is broken for horizontal scrollbars
If you have a nested horizontal ScrollView which uses bars as scroll type, inside a vertical ScrollView, then the touch transformation is broken for the horizontal scroll-bar inside the horizontal ScrollView. It is only noticeable though, if the vertical ScrollView is not starting at `x=0` in window coordinates.

I have added a code snippet to reproduce the error (see below). It is based on kived's nested ScrollView example ([from here](https://gist.github.com/kived/2aa1b6814979340598a7)).

What I also found out was:
- The issue does not occur if the horizontal ScrollView is using content as scroll type.
- The issue does not appear (as already mentioned above) if the vertical ScrollView is starting at `x=0` in window coordinates
- Also the issue does not appear on Kivy 1.8.0. On 1.9.0 and 1.9.1 it appears. (Thanks @bionoid for hinting me to test the different versions.)

```
import kivy

from kivy.app import App
from kivy.lang import Builder

import sys

if 'horizontal' in sys.argv:
    sys.argv.remove('horizontal')
    fmt = {
        'horizontal': 'vertical',
        'x': 'y',
        'y': 'x',
        'width': 'height',
        'height': 'width',
        'col': 'row',
        'row': 'col',
    }
else:
    fmt = {
        'horizontal': 'horizontal',
        'x': 'x',
        'y': 'y',
        'width': 'width',
        'height': 'height',
        'col': 'col',
        'row': 'row',
    }

root = Builder.load_string('''
BoxLayout:
    orientation: 'horizontal'
    BoxLayout:
        orientation: 'horizontal'
        size_hint_x: None
        width: 150
        canvas.before:
            Color:
                rgba: 0, 0, 1, 1
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            text: "I mess up the nested horizontal scrollbar."
            size_hint_x: None
            width: self.parent.width
            text_size: self.parent.width, None
            max_lines: 5
    BoxLayout:
        orientation: '{horizontal}'
        BoxLayout:
            orientation: '{horizontal}'
            size_hint_{x}: None
            {width}: 0
            Widget:
                id: quarter
            Widget
            Widget
            BoxLayout:
                orientation: '{horizontal}'
                Widget:
                    id: eighth
                Widget
        ScrollView:
            canvas.before:
                Color:
                    rgba: 1, 1, 1, 0.3
                Rectangle:
                    pos: self.pos
                    size: self.size
            scroll_type: ['bars']
            bar_width: 50
            GridLayout:
                {col}s: 1
                size_hint_{y}: None
                {height}: self.minimum_{height}
                {row}_default_{height}: quarter.{height}
                {row}_force_default: True
                Widget
                BoxLayout:
                    orientation: '{horizontal}'
                    canvas.before:
                        Color:
                            rgba: 1, 0, 0, 0.5
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    Widget
                    ScrollView:
                        scroll_type: ['bars']
                        bar_width: 50
                        GridLayout:
                            {col}s: 1
                            size_hint_{y}: None
                            size_hint_{x}: 2.0
                            {height}: self.minimum_{height}
                            {row}_default_{height}: eighth.{height}
                            {row}_force_default: True
                            canvas.before:
                                Color:
                                    rgba: 1, 1, 1, 1
                                Rectangle:
                                    pos: self.pos
                                    size: self.size
                            Widget
                            Label:
                                text: 'Hi!'
                                canvas.before:
                                    Color:
                                        rgba: 0, 0, 1, 0.5
                                    Rectangle:
                                        pos: self.pos
                                        size: self.size
                            Widget
                    Widget
                Widget
'''.format(**fmt))

class TestApp(App):
    def build(self):
        return root

if __name__ == '__main__':
    TestApp().run()
```

### PR DESCRIPTION
**Pull request by sugarlata**
See [792529f](https://github.com/sugarlata/kivy/commit/792529ff410db392fd03cf23124d8e07990d836a) for more details.

### CODE REVIEW

**Comment by KeyWeeUsr** [comment]
The horizontal/vertical bar of the nested `ScrollView` is still broken and takes width/height of the whole widget at the beginning. When touched and moved, the bar resizes itself to the expected(working) size. @sugarlata I wonder, could you check that too?

**Comment by sugarlata** [comment]
Yep, I can have a look and see whether I can figure it out.

**Comment by matham** [comment]
So I ran into an issue with this PR using the following code tested by moving the mouse a little bit:

```py
from kivy.lang import Builder
from kivy.app import runTouchApp

w = Builder.load_string('''
ScrollView:
    scroll_type: ['bars']
    on_touch_move: print('s', args[1].grab_current, args[1])
    Widget:
        on_touch_move: print('w', args[1].grab_current, args[1])
''')

runTouchApp(w)
```

With 1.10.1 I get
```
s None <MouseMotionEvent spos=(0.42125, 0.7833333333333333) pos=(337.0, 470.0)>
w None <MouseMotionEvent spos=(0.42125, 0.7833333333333333) pos=(337.0, 470.0)>
s None <MouseMotionEvent spos=(0.42125, 0.7816666666666667) pos=(337.0, 469.00000000000006)>
w None <MouseMotionEvent spos=(0.42125, 0.7816666666666667) pos=(337.0, 469.00000000000006)>
```

With this PR merged I get:
```
s None <MouseMotionEvent spos=(0.28625, 0.8283333333333334) pos=(229.0, 497.0)>
w None <MouseMotionEvent spos=(0.28625, 0.8283333333333334) pos=(229.0, 497.0)>
s <kivy.uix.scrollview.ScrollView object at 0x000001AFCA6D2B40> <MouseMotionEvent spos=(0.28625, 0.8283333333333334) pos=(229.0, 497.0)>
w <kivy.uix.scrollview.ScrollView object at 0x000001AFCA6D2B40> <MouseMotionEvent spos=(0.28625, 0.8283333333333334) pos=(229.0, 497.0)>
s None <MouseMotionEvent spos=(0.33875, 0.6766666666666667) pos=(271.0, 406.00000000000006)>
w None <MouseMotionEvent spos=(0.33875, 0.6766666666666667) pos=(271.0, 406.00000000000006)>
s <kivy.uix.scrollview.ScrollView object at 0x000001AFCA6D2B40> <MouseMotionEvent spos=(0.33875, 0.6766666666666667) pos=(271.0, 406.00000000000006)>
w <kivy.uix.scrollview.ScrollView object at 0x000001AFCA6D2B40> <MouseMotionEvent spos=(0.33875, 0.6766666666666667) pos=(271.0, 406.00000000000006)>
```

With 1.10.0, we get one call per widget, with `grab_current` None. With master, you two calls for each touch, once with `grab_current` None and the other time with it set to the sv. Obviously I can just ignore it if it's not None, but I'm wondering if this is the correct behavior.

On second thought, when `grab_current` is not None, the widget that gets the callback should probably not propagate the touch to its children as it was meant for it due to the grab I think.

Also, the same issue happens with touch_up.

**Comment by sugarlata** [comment]
I'll take a look and see if I can correct it. I was under the impression that grab_current was set to the widget/scrollview after on_touch_down in 1.10.0
It's been a bit of a learning curve to become familiar with the scrollview module, at this point I would say that it isn't the correct behaviour, I'll take a look at the program logic inside a nested scroll and outside and see if I can correct this.

**Comment by matham** [comment]
I'd like to revert this soon if there's no fix because there are multiple issues related this that I ran into (one is not even nested, yet the neighboring widgets to the right get a touch move event that the scroll view should have and used to filter out because otherwise the scrollview children think the touch is above them, when the scrollview actually clipped them).

**Comment by matham** [comment]
Here's the revert PR: https://github.com/kivy/kivy/pull/5395.

**Comment by sugarlata** [comment]
Unfortunately haven't had the time to begin working on a fix, I think it
might take a little longer than expected, so likely to be a work in
progress for a little while longer yet. Also discovered a problem when
using a scrollview in another root element. Can't give a timeframe on it
unfortunately, have some other more pressing projects currently, but want
to get this figured out.

**Pull request merged**
