### PR TITLE
Fix file opening for vkeyboard

### LINKED ISSUE #5003: Examples: Keyboard & KeyboardListener
### Versions

* Python: 2.7, 3.5
* OS: Win8.1, 64bit
* Kivy: master, wheels

### Description

Example `examples/keyboard/main.py` dead for py3(.5.3).

> UnicodeDecodeError: 'charmap' codec can't decode byte 0x88 in position 3960

Similar for `examples/widgets/keyboardlistener.py` after pressed modifier (Ctrl, Shift)

> UnicodeEncodeError: 'charmap' codec can't encode character '\u0131' in position 12 ...

### PR DESCRIPTION
**Pull request by KeyWeeUsr**
Closes #5003 Fixes the example too for different type of input.

### CODE REVIEW

**Comment by akshayaurora** [comment]
@KeyWeeUsr it works but I did not have the issue to begin with.

**Comment by akshayaurora** [comment]
@KeyWeeUsr has some one other than you been able to reproduce this ?

**Comment by KeyWeeUsr** [comment]
Oh, it was just a ping to check if it works after this change for you on OSX :P

Well, I don't know about anyone else even trying to reproduce, so... until someone does, no.

**Comment by akshayaurora** [comment]
@dessant @matham since you folks use windows, could you please check if you have this issue and guide this to a merge if it fixes the issue?

**Pull request merged**
