### PR TITLE
Split behaviors into individual module files. Fixes #3331.

### LINKED ISSUE #3331: Turn behaviors.py into a sub-package with one behavior/module
```
(08:53:33 PM) qua-non: vote for breaking up behaviors into module dir with different files for each behavior
(08:53:35 PM) qua-non: +1
(08:53:48 PM) kived: +1
(08:54:20 PM) dessant: +1
(08:54:32 PM) kived: the monolithic behaviors.py is getting too big
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/13079510-turn-behaviors-py-into-a-sub-package-with-one-behavior-module?utm_campaign=plugin&utm_content=tracker%2F42681&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F42681&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by matham**
Split behaviors into individual module files. Fixes #3331.

### CODE REVIEW

**Comment by dessant** [comment]
Thankly. :+1:

**Comment by DavidA2014** [comment]
The files in kivy.uix.behaviors don't show up in the installation directory after running:

sudo python3 setup.py install

**Comment by pythonic64** [comment]
Because 'kivy.uix.behaviors' isn't added in setup.py [packages](https://github.com/kivy/kivy/blob/master/setup.py#L888) list.

**Comment by matham** [comment]
Should be fixed now with https://github.com/kivy/kivy/commit/62e475656524d0845e8c348fb6ba8f2bde3544af.

**Comment by pythonic64** [comment]
:+1:

**Comment by DavidA2014** [comment]
Thanks

**Pull request merged**
