### PR TITLE
kivy.utils.platform is a string and it is not callable anymore

### PR DESCRIPTION
**Pull request by dessant**

### CODE REVIEW

**Comment by dessant** [comment]
Should be listed here after merging: https://github.com/kivy/kivy/wiki/Breaking-changes-in-Kivy-2.0.

**Comment by matham** [comment]
Why?

**Comment by dessant** [comment]
@matham, why not? :dancer: 
It was deprecated 3 years ago.

**Comment by matham** [comment]
Ok.

**Pull request merged**
