### PR TITLE
Create gl2.h

### PR DESCRIPTION
**Pull request by Why7090**
from https://www.khronos.org/registry/gles/api/GLES2/gl2.h

### CODE REVIEW

**Comment by inclement** [comment]
Why should this be included in Kivy? Shouldn't it be provided by some appropriate package, e.g. mesa on linux?

**Comment by Kovak** [comment]
This file already exists in kivy: 
https://github.com/kivy/kivy/blob/master/kivy/tools/gles_compat/gl2.h

**Comment by Why7090** [comment]
because we need this to install kivent

**Comment by Kovak** [comment]
What platform? KivEnt already checks for this file inside the tools/gles_compat/gl2.h folder.

**Comment by Why7090** [comment]
ubuntudy@ubuntu:~/Downloads/kivy-kivent/modules/core$ sudo python3 setup.py build_ext install
[sudo] password for ubuntudy: 
[INFO   ] [Logger      ] Record log in /home/ubuntudy/.kivy/logs/kivy_16-01-27_14.txt
[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v3.4.3 (default, Mar 26 2015, 22:03:40) 
[GCC 4.9.2]
running build_ext
building 'kivent_core.memory_handlers.pool' extension
creating build/temp.linux-x86_64-3.4/kivent_core/memory_handlers
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/lib/python3/dist-packages/kivy/graphics -I/usr/lib/python3/dist-packages/kivy/tools/gles_compat -I/usr/include/python3.4m -c kivent_core/memory_handlers/pool.c -o build/temp.linux-x86_64-3.4/kivent_core/memory_handlers/pool.o -std=c99 -ffast-math
creating build/lib.linux-x86_64-3.4
creating build/lib.linux-x86_64-3.4/kivent_core
creating build/lib.linux-x86_64-3.4/kivent_core/memory_handlers
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.4/kivent_core/memory_handlers/pool.o -o build/lib.linux-x86_64-3.4/kivent_core/memory_handlers/pool.cpython-34m.so
building 'kivent_core.rendering.model' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/lib/python3/dist-packages/kivy/graphics -I/usr/lib/python3/dist-packages/kivy/tools/gles_compat -I/usr/include/python3.4m -c kivent_core/rendering/model.c -o build/temp.linux-x86_64-3.4/kivent_core/rendering/model.o -std=c99 -ffast-math
In file included from kivent_core/rendering/model.c:260:0:
/usr/lib/python3/dist-packages/kivy/graphics/gl_redirect.h:31:26: fatal error: GLES2/gl2.h: 没有那个文件或目录
 #   include <GLES2/gl2.h>
                          ^
compilation terminated.
 error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by Kovak** [comment]
It looks like for your platform this should actually be found outside the kivy installation:
https://github.com/kivy/kivy/blob/master/setup.py#L354

make sure the location of your gles2 is on your path and it should build without adding the header to kivy

**Comment by dessant** [comment]
@Why7090, @kovak, can this be closed?

**Pull request closed without merging**
