### PR TITLE
Many small fixes

### PR DESCRIPTION
**Pull request by merriam**
This fixes a bunch of small nits today:

1.  Upgraded the examples/audio to provide buttons and samples to play mp3 and ogg files.  It helps in figuring out what actually works in audio.
2.  kivy/tests/test_font.py would leave a Unicode font after running, which showed up in git diff.   It now removes the font after testing.
3.  setup.py had some PEP8 warnings that I fixed while looking for another bug.
4.  kivy/utils.py got better documentation, PEP8 cleanup, and better testing to bring its test coverage up to 100%.
5.  Fixed a misspelling in the documentation of kivy/modules/__init__.py

Now Git is annoyingly confused, and keeps trying to add in a 2012 version of some core/text files and I had to run another commit to remove them.  Sorry.

### CODE REVIEW

**Comment by akshayaurora** [comment]
@merriam Hey thanks for looking into helping,  I see you are new to git,  there are numerous issues with this pr mostly due to conflicts and unneeded commits being included. 

Could you start fresh and do one pr for one feature/fix with doc changes separate from the code fix unless they are about the same thing in the same file?

This would help us to maintain a simple git history. This would also help us keep doc changes form code changes separate.

Over all, you have done a nice job. Just try and do it in a cleaner manner with one pr for one fix.

**Comment by merriam** [comment]
Hi Akshay,

I'm not following you.

Each commit does do one small thing.   It sounds like you are asking me to
submit each commit as a PR.  The history is based on commits.  I'm willing
to do whatever is asked.  However, if dealing with GitHub becomes more than
25% of the time for actually making changes, I will drop the project.

Life is too short to squirrel cage.

Let me know if I should be throwing each commit as a PR.

Charles

**Comment by dessant** [comment]
@merriam i think the main problem is the one which you pointed out here https://github.com/kivy/kivy/pull/2938#commitcomment-9470906, those commits have nothing to do with any pr, and when they are merged, they pollute the commit history.

Maybe the problem is that your master branch is messed up already, i'm not sure why these commits keep sneaking back.

But you don't have to do a new pr for every commit, just divide them in bigger groups, like:

- changes which affect doctrings (typos, grammar, wording) can go in a pr (this can contain changes across multiple files)
- a new pr for doc changes that extend the documentation of a module or section/topic (multiple files, if the changes belong to the same domain, it can also include simple typo fixes)
- a new pr for code changes (+ doc if needed) with a description on what the change fixes/improves (multiple files, if needed)

This is a standard policy for any project, and it helps a lot in debugging, changelogs, etc.

It all comes down to keeping things clean an compartmentalized.

**Comment by matham** [comment]
Also, in case you're not aware of it, using git rebase with cherry pick will let you rebase onto clean branches for each pr you do.

**Comment by merriam** [comment]
Broken up and resubmitted.  All done.

**Pull request closed without merging**
