### PR TITLE
Graphics: Check whether user updated GL instructions from external thread.

### PR DESCRIPTION
**Pull request by matham**
Maintainer merge checklist
* [x] Title is descriptive/clear for inclusion in release notes.
* [x] Applied a `Component: xxx` label.
* [ ] Applied the `api-deprecation` or `api-break` label.
* [x] Applied the `release-highlight` label to be highlighted in release notes.
* [x] Added to the milestone version it was merged into.
* [x] **Unittests** are included in PR.
* [x] Properly documented, including `versionadded`, `versionchanged` as needed.

New users often don't realize that you cannot set graphics or change properties that then set graphics properties outside the main Kivy thread. But they notice something is wrong, but don't know why.

This adds a option that will error out of graphics are created or updated outside the main kivy thread. By default the option is ON, but it can be turned off in config.

In terms of performance loss, if the option is turned OFF, there's basically no additional cost. But if it's turned ON, it's slower, but only in the tens of microseconds per property, which I think is negligible and worth making Kivy more bullet proof and friendlier to new users.

Here is the performance testing code:

```py
from timeit import timeit
from kivy.config import Config
from kivy.uix.widget import Widget
from kivy.graphics import Rectangle, Color, Line

widget = Widget()
with widget.canvas:
    color = Color()
    rect = Rectangle()
    line = Line()

number = 1_000_000
values = []
for val in ('0', '1'):
    Config.set('graphics', 'verify_gl_main_thread', val)
    values.append(sum(timeit(setup='from __main__ import color, rect, line', stmt='color.rgb = .1, .2, .3', number=number // 10) for _ in range(10)))
    values.append(sum(timeit(setup='from __main__ import color, rect, line', stmt='rect.pos = .1, .2', number=number // 10) for _ in range(10)))
    values.append(sum(timeit(setup='from __main__ import color, rect, line', stmt='line.points = [1, 2, 3, 4, 5, 6]', number=number // 10) for _ in range(10)))

for i in range(3):
    print(f'{values[i]:0.4f} -> {values[i + 3]:0.4f}: {(values[i + 3] - values[i]) / values[i] * 100:0.2f}%, {((values[i + 3] - values[i]) / number):0.2E} difference')
```

This prints:
```
0.2593 -> 0.3300: 27.24%, 7.07E-08 difference
0.0428 -> 0.0453: 5.75%, 2.46E-09 difference
0.1718 -> 0.2618: 52.41%, 9.00E-08 difference
```
The percent may seem large, but look at the actual increase, which is in microseconds.

I also ran it with master (where setting the config option does nothing), and it printed:
```
0.2397 -> 0.2262: -5.64%, -1.35E-08 difference
0.0447 -> 0.0471: 5.41%, 2.42E-09 difference
0.1762 -> 0.1735: -1.51%, -2.67E-09 difference
```
which shows that when the option is turned OFF (compare first number to the first number abover), it basically is the same.

### CODE REVIEW

**Comment by tshirtman** [comment]
This looks like a great idea, didn't test yet, but i believe the numbers you quoted should be fine, especially as it's possible to disable it when releasing your apps without any downside, as any issue of this kind should have been caught during development, code looks fine.

**Comment by matham** [comment]
Looks like it required a 64 bit in to store the thread id that's why it originally failed on linux/osx.

Unit tests, testing both enabling and disabling the config options and verifying it raises/doesn't raise a exception is included in the PR.

**Comment by xloem** [comment]
I reviewed the last commit and found python uses `unsigned long` ( https://github.com/python/cpython/blob/master/Modules/_threadmodule.c#L1208 64-bits on 64-bit systems) for the datatype in question.  Under the hood it seems to make the value in a platform-dependent way.  I'm happy to see automerge.  I imagine software projects growing as big wikis, like wikipedia.

**Comment by matham** [comment]
Thanks for the info about `unsigned long`, I updated the code to use it.

**Pull request merged**
