### PR TITLE
Update properties docs

### PR DESCRIPTION
**Pull request by user5061**
[Here](https://gist.github.com/user5061/7433e8049c9f44c755180b85f6c05139) is the code to reproduce the behavior in the commit. The same can be replicated with DictProperty, ObjectProperty, and probably all properties. I only tested those 3 Kivy properties though.

### CODE REVIEW

**Comment by KeyWeeUsr** [comment]
May seem strange, but it's kind of obvious, because you change a value of a different object(the dictionary) and the check is only set for the object that is instance of `ListProperty`, which inherits from EventDispatcher.

I wonder if it behaves the same e.g. for `ListProperty([0, ListProperty([1, 2])])`

**Comment by user5061** [comment]
I initially incorrectly assumed that properties create a deepcopy of the object. Perhaps #4571 should be used instead of this PR.

**Comment by rafalo1333** [comment]
Properties must be declared at class level, I do not think KeyWeeUsr example is possible to produce with Kivy.

**Comment by KeyWeeUsr** [comment]
@user5061 Oh, I thought I was alone with that error. Anyway, I was only curious if that'd work. If, then maybe this way it could store an additional info, which could result in making ping from nested Properties possible e.g.:

```
p = ListProperty([0, 1])
p[1] = ListProperty([1, 2], parent=p)
```

Otherwise, I think the addition to docs is good, because it probably isn't mentioned there and will spare troubles for someone thinking about why this or that don't work, so... I'd merge it, though I don't know if I can :smile:

**Comment by matham** [comment]
I'd say that the top part is good, but I'd remove everything after `Another example::`. From there on it just adds an example that is not recommended (will it even work?) usage of properties and is already clear by the first example.

I'd also change `The same holds true for all kivy properties.` to `The same holds true for all container type kivy properties.` For `ObjectProperty` e.g. even the top level will not be tracked. So it only applies for list/dict properties.

**Comment by user5061** [comment]
@matham Ah yes, there is already a "Warning"-section in ObjectProperty docs, which makes that part of the PR redundant. What's the procedure when a PR should be changed before pulled? Should I change it?

**Pull request merged**
