### PR TITLE
Method to retrieve the matrix

### PR DESCRIPTION
**Pull request by olymk2**
Add a new method which will return the value of the matrix which we can reference in python code

### CODE REVIEW

**Comment by tito** [comment]
I wonder why we didn't have it in the first case :)
Can you add the documentation for it, with a versionadded tag to 1.9 ?

Thanks!

**Comment by olymk2** [comment]
I am happy to but where, looking in kivy/doc/sources i dont see an obvious place to add any docs or existing docs for matrix ? is this a different repo ?

**Comment by olymk2** [comment]
figured out you just wanted a doc string, added :)

**Comment by dessant** [comment]
:+1:

**Pull request merged**
