### PR TITLE
BUGFIX: Parser.execute_directive() doesn't use resource_find() for in…

### PR DESCRIPTION
**Pull request by ericatkin**
…clude directive.

### CODE REVIEW

**Comment by rafalo1333** [comment]
I've tested on 1.9.1 and it fixes the issue of not recognizing the kv files loaded multiple times with #:include directive.

**Comment by akshayaurora** [comment]
I can't reproduce this, please a provide a snippet for the issue this is supposed to solve.

**Comment by rafalo1333** [comment]
@akshayaurora https://bitbucket.org/rafalo1333/kvlangincludekverror/src

**Comment by akshayaurora** [comment]
@ericatkin @rafalo1333 thanks

**Pull request merged**
