### PR TITLE
Prevent error if canvas is not setup yet

### PR DESCRIPTION
**Pull request by Zen-CODE**
references issue #4736

### CODE REVIEW

**Comment by udiboy1209** [comment]
@Zen-CODE your doesn't fix the error mentioned in the issue. I still get the same error for both python 2.7 and 3.5

**Comment by Zen-CODE** [comment]
@udiboy1209. Please can you tell me how you make it error, or post an example? The fix mainly addresses setting on initialization, but it works for me whatever I try...

**Comment by udiboy1209** [comment]
I am running the same example the OP posted in #4736 and getting the same error he gets. I checked the installed textinput.py and it does have your change. Also check my latest comment on that issue's thread.

**Comment by Zen-CODE** [comment]
@usiboy1209. Thanks. Latest push should fix, but it's hackish. I think it's probably better to re-visit the implementation....

**Comment by akshayaurora** [comment]
@Zen-CODE thanks

**Pull request merged**
