### PR TITLE
Cython22

### PR DESCRIPTION
**Pull request by DragonSA**
Add support for cython 0.22.

### CODE REVIEW

**Comment by tito** [comment]
Good to me. @kived ?

**Comment by akshayaurora** [comment]
Won't this result in a significant performance hit?

**Comment by tito** [comment]
no idea, need to be tested.

**Comment by kived** [comment]
I already have a PR which does the same thing. But using except * does cause a performance hit, as the interpreter will check for an exception after every call to those functions. We discussed switching the functions all to int except -1, which won't check for exceptions unless the function returns -1. Should be better, but it means adding return 0 to every apply function.

**Comment by DragonSA** [comment]
Just a warning about this pull request: this patch (and others) on kivy 1.8.0 are causing a lot of failed unit tests (errors=2, failures=9).  This could be other issues with FreeBSD however I haven't isolated the problem (more difficult as FreeBSD ships with cython 0.22 - hence this patch).

**Comment by DragonSA** [comment]
Never mind, the failures come from audio and font.  No issues with unit tests from graphics.  Apologies for the noise.

**Comment by kived** [comment]
FYI - you can use pip to install a specific version of Cython.

**Comment by tito** [comment]
Then +1 for adding return 0.

**Comment by kived** [comment]
At this point, I'm leaning toward that option as well. The Cython devs haven't even acknowledged the bug report, so it may be better to take the slight performance hit to avoid waiting on them.

**Comment by matham** [comment]
Yep, agree that the return 0/-1 is a good choice at this point. But not before the release.

**Comment by matham** [comment]
We'll just have to make sure as well that exception previously eaten by cython will not be forwarded. E.g. textures to large etc, in the past those did not cause an exception because cython ignored them and just printed that.

**Comment by inclement** [comment]
I did a PR to add 'except -1' instead, at https://github.com/kivy/kivy/pull/3283.

**Comment by akshayaurora** [comment]
closing in favor of https://github.com/kivy/kivy/pull/3283

**Pull request closed without merging**
