### PR TITLE
Add shape collision example

### PR DESCRIPTION
**Pull request by KeyWeeUsr**
Pretty much ~100 lines of commented stuff in there, but should give a really good look on how powerful and readable Kivy + Python is with multitouch and collisions. This example provides 3 classes:

* BaseShape, which is just an abstracted behavior for moving everything through `on_pos`
* RegularShape, a real, regular shape with a center == widget's center and increasing the amount of edges up to circle-like shape within the widget's size as a bounding box. Doing it manually was quicker than trying to use `Line` or `Ellipse` as I still needed to construct a `Mesh`, thus I'd end up with constructing twice that much stuff.
* MeshShape, a real, irregular and _convex_ shape based on an inputted array of points. The basic problem was that no editor is capable of creating a useful, out-of-box working set of points i.e. if I put there _raw_ points made with Pen in Gimp/Illustrator, it wouldn't display the points correctly, thus a correction with pushing the bottom-left part of the points (imagine it like a 2D bounding box) to the widget's origin was necessary

In a real application the `MeshShape` could be scaled to a capability of handling multiple subparts of a huge mesh like in my silly issue (#5040), therefore it wouldn't be convex-only, however that would take a long while to make it (if someone feels adventurous, though I might do it in future).

However, I can't make `BaseShape.move_collider()` to work, because for some reason the points are still the same. Probably I made some silly mistake somewhere, but I just don't see it. Help welcome? 😄

### CODE REVIEW

**Comment by KeyWeeUsr** [comment]
For some reason `Line(circle=...)` won't move with touch, but classic `Line` or `Point` will. `Point` is prettier anyway:

image

**Comment by matham** [comment]
I wonder if this may be too complex for an example. It has lots of parts with custom algorithms. But perhaps that's needed so people have examples of a more complex app? Also, we have garden.collider for non-standard shape collision detection.

**Comment by KeyWeeUsr** [comment]
From algorithms, there's PIP only, the rest is Pythagorean theorem and playing with max/min (edges) of an array of points. It might seem maybe too much if you mean the mesh points correction, but that's kind of necessary and not too obvious, especially for the beginners (definitely wasn't obvious to me 😆 ) for creating a custom 2D shapes, which might be later used in e.g. kivent (didn't see anything like that in it).

If not, point me to the specific lines, maybe I might be able to simplify or remove it ^^

**Comment by matham** [comment]
That was kind-of my point, an example should probably not include algorithms as that takes away a bit from the purpose of showing how to use kivy itself, rather than also having to understand algorithms used there, which at that point may belong on the wiki instead. However, it's probably fine for a few examples. Or maybe we should have a folder for more advanced examples.

That said I also don't us to be responsible for maintaining these more advanced examples, specifically by having people (or e.g. potential students) opening PRs to fix whatever subtlety you may have missed. But I guess that's not that strong of reason to reject this.

**Comment by KeyWeeUsr** [comment]
Yeah, I agree the maintaining could lead to problems if someone decides to implement completely new stuff into the example, though if such thing would be rejected (I don't see the rest of the examples "reworked" anyway), then it might work i.e. fixes only.

Anyway, I'm also ok with the wiki if it's a better idea.

**Comment by matham** [comment]
I think this is fine. Maybe just add a notice that it's just meant as a demo. Although I'm not really sure it's needed. Upto to you.

**Comment by KeyWeeUsr** [comment]
I found a little bug with always true for `shape_collide` as `return` from a function means true, though otherwise it should be ok.

**Pull request merged**
