### PR TITLE
MouseHoverEventTestCase: Dispatching event on_cursor_leave to cleanup some tests

### PR DESCRIPTION
**Pull request by pythonic64**
Maintainer merge checklist
* [x] Title is descriptive/clear for inclusion in release notes.
* [x] Applied a `Component: xxx` label.
* [ ] Applied the `api-deprecation` or `api-break` label.
* [ ] Applied the `release-highlight` label to be highlighted in release notes.
* [x] Added to the milestone version it was merged into.
* [ ] **Unittests** are included in PR.
* [ ] Properly documented, including `versionadded`, `versionchanged` as needed.

### CODE REVIEW

**Comment by pythonic64** [comment]
@matham Can you review this pull request? We will have to disable `MouseHoverEventTestCase` again as tests in `MultitouchSimulatorTestCase` can still fail although they passed in https://github.com/kivy/kivy/pull/7483.

**Comment by matham** [comment]
I'm not sure what to make of this because as you noted the tests fail again. I would rather not merge something that causes the tests to fail. Is the changes needed to properly cleanup and the test failing is just a consequence, or are the changes to try to fix the failing tests?

**Comment by pythonic64** [comment]
Changes in this request ensure that "end" event is dispatched to cleanup internals of `EventLoop` and they are not fix or cause of failing tests in `MultitouchSimulatorTestCase`. I'm still trying some ideas to fix that failing class.

**Comment by matham** [comment]
Maybe we can just disable all these tests on Windows CI for now, if you want to merge this before figuring out the issues.

BTW, have you tries running mint in a VM to see if perhaps you can directly replicate the issue like @Zen-CODE mentioned? That could help!?

**Comment by pythonic64** [comment]
I would rather disable `render` method of `MultitouchSimulatorTestCase` by merging https://github.com/kivy/kivy/pull/7502 and then rebase this request.

**Review by matham — DISMISSED** [review]

**Review by matham — APPROVED** [review]

**Pull request merged**
