### PR TITLE
Build python 3.9 wheels for RPi

### PR DESCRIPTION
**Pull request by matham**
Maintainer merge checklist
* [ ] Title is descriptive/clear for inclusion in release notes.
* [ ] Applied a `Component: xxx` label.
* [ ] Applied the `api-deprecation` or `api-break` label.
* [ ] Applied the `release-highlight` label to be highlighted in release notes.
* [ ] Added to the milestone version it was merged into.
* [ ] **Unittests** are included in PR.
* [ ] Properly documented, including `versionadded`, `versionchanged` as needed.

Follow up from https://github.com/piwheels/packages/issues/289.

### CODE REVIEW

**Comment by matham** [comment]
It would be great if someone with a pi can test the py3.9 wheels when they are generated (assuming it works).

**Comment by matham** [comment]
Wheels can be found here: https://github.com/kivy/kivy/actions/runs/2054749180.

**Comment by peanball** [comment]
I will try on the weekend.

**Comment by misl6** [comment]
Hi @peanball ,

That was on my task list before `2.2.0` release, but unfortunately, the chip shortages also affected RPi, and I wasn't able to find an RPi to perform some tests.

Did you had the chance to test the `3.9` wheels ?

**Comment by peanball** [comment]
I forgot about it to be honest. At the time I didn’t have 3.9 available on raspbian. I will find some time to look into it.On 2. Apr 2023, at 12:12, Mirko Galimberti ***@***.***> wrote:﻿
Hi @peanball ,
That was on my task list before 2.2.0 release, but unfortunately, the chip shortages also affected RPi, and I wasn't able to find an RPi to perform some tests.
Did you had the chance to test the 3.9 wheels ?

**Comment by misl6** [comment]
As discussed with @akshayaurora on Discord, since the build for RPi artifacts is already broken, even if we can't perform all the tests on real hardware, the PR will be merged as-is.

That will allow us ~2 more weeks before `2.2.0.rc1` to complete some more exhaustive testing.

**Pull request merged**
