### PR TITLE
Adding an indeterminate mode to ProgressBar

### PR DESCRIPTION
**Pull request by Vagdish**
By passing None as value or as value_normalized.
This commit simplify the pull request 3093 (no new method added) but the
indeterminate mode is still hackable through style.kv

### CODE REVIEW

**Comment by Vagdish** [comment]
I'm very sorry to open a new pull request for this change. I've done some mistakes with my git repo.

Well, this is similar to #3093 but without adding new methods to API. Devs can still easily change the visuals through style.kv

**Comment by tito** [comment]
Thanks a lot for your contribution! I'm starting to be worried about the complexity of the kv rule. Would you be able to try the separation within python instead? Ie, pos/size/border are depending of a pos/size/border_indeterminate if the current mode is indeterminate, otherwise use the pos/size/border_normal
(ie, you'll need to add 6 variables, and switch from one to another depending the mode).

Unsure exactly about the code in the end, but this is getting unreadable :)

**Comment by Vagdish** [comment]
Yes, it could be done within python. I'll update the pull request according to your advice and put the sin-math-magic into python.

**Comment by KeyWeeUsr** [comment]
@Vagdish Any progress with this?

**Pull request closed without merging**
