### PR TITLE
[WIP] Feature: refactor OpenGL implementation

### PR DESCRIPTION
**Pull request by tito**
This is a major rework of OpenGL internals within Kivy to:
- support [ANGLE](https://github.com/MSOpenTech/angle) on Windows (see https://github.com/kivy/kivy/pull/4343 for the initial motivation)
- not statically link to a OpenGL library for each graphics python extension
- make an OpenGL backend interface available to use for each graphics python extension
- implement multiple backend such as
  - sdl: use `SDL_GL_GetProcAddress` to look at start all the GL symbols
  - static: wire OpenGL functions at link time during compilation. This can fail if the platform miss some OpenGL functions.
  - mock: empty implementation of all GL functions
  - debug: wrapper around the current loaded backend to print the call and results
  - angle: redirect to sdl, but since the Windows require 3 lines to be executed for ANGLE, we need to make it look like a backend

Changes:
- all `c_opengl_`\* are gone
- all modules now just use `kivy.gragphics.cgl` directly
- all backends are declared like `kivy.graphics.cgl_<NAME>`
- ship GLES/KHR headers
- `USE_OPENGL_MOCK`, `USE_GLEW`, are gone.

Environment:
- `KIVY_GL_BACKEND`: {sdl,static,mock}
- `KIVY_GL_DEBUG`: {0,1}

Examples:

``` bash
# Run with mock
KIVY_GL_BACKEND=mock python ...

# Run in debug mode
KIVY_GL_DEBUG=1 KIVY_GL_BACKEND=sdl python ...

# Run with ANGLE (windows only)
KIVY_GL_BACKEND=angle python ...
```

TODO:
- tests on all platforms
- implement GLEW backend
- fixes `debug` backend (it prints, but nothing is displayed on screen)
- enhance debug to print OpenGL call to a file (can be cool for unit tests)
- fixes missing GLES functions

### CODE REVIEW

**Comment by tshirtman** [comment]
in the examples: `KIVY_GL_BACKEND=1` to run with angle on windows, didn't you mean `KIVY_GL_BACKEND=angle` ?

**Comment by tito** [comment]
Yes, thanks, fixed.

**Comment by matham** [comment]
I was playing around with it and looks great. I added some changes on top of this branch to get glew working and you can see it here: https://github.com/kivy/kivy/pull/4397.

> fixes debug backend (it prints, but nothing is displayed on screen)

Yeah, I noticed that. I tried printing to debug in the cython code but it didn't print. I had to print it to Logger for it to show.

> enhance debug to print OpenGL call to a file (can be cool for unit tests)

That is a good idea. Although maybe being able to set a callback is better? That way we can pass a print function or what I think may be a better default - Logger.debug.

**Comment by matham** [comment]
@Kovak @thopiekar This moves the gl headers (including config.h/pxi) fro  kivy/graphics to kivy/include. It also creates a new module at kivy/graphics/cgl_backend.

Docs on how to use this is at https://github.com/kivy/kivy/blob/master/kivy/graphics/cgl.pyx#L1.

Also, this should be tested on android, ios, rpi, and mali. Those are the OSs with potential issues. But it should be an easy fix I believe if there are issues.

**Comment by jimanvlad** [comment]
Hi, 

Would:
```
import os
os.environ['KIVY_GL_BACKEND'] = 'angle'
```
before importing kivy 1.9.2 dev be sufficient to test this?

I am mostly interested in getting around the bug where it says minimum version is openGL 2.0 and it thinks I have 1.1.

**Comment by matham** [comment]
angle is only available for 3.5+ and you need to download kivy.deps.angle. But yeah, `os.environ['KIVY_GL_BACKEND'] = 'angle'` is how you'd use it.

**Comment by jimanvlad** [comment]
But that would only work on the current GitHub kivy master branch rather than the one you get through the usual pip install kivy right?

**Comment by matham** [comment]
Yes. You can also get it using the nightly wheels: https://kivy.org/docs/installation/installation-windows.html#nightly-wheel-installation. Just remember to upgrade all the kivy.deps.xxx you have installed to their latest versions from pypi.

**Comment by matham** [comment]
Sorry, I think it's actually `angle_sdl2`, not `angle`.

**Comment by jimanvlad** [comment]
I get:
```
[CRITICAL] [Window      ] Unable to find any valuable Window provider.
sdl2 - ValueError:  angle_sdl2 is not a recognized GL backend
```
with angle_sl2 and the latest nightly build.

I also get a similar:
```
[CRITICAL] [Window      ] Unable to find any valuable Window provider.
sdl2 - ValueError:  angle is not a recognized GL backend
```

with `os.environ['KIVY_GL_BACKEND'] = ' angle'`. What am I doing wrong?

Vlad

**Comment by dessant** [comment]
Your strings start with a whitespace.

**Comment by jimanvlad** [comment]
Silly me, thanks. Now it seems to use ANGLE but I still have the OpenGL 1.1 problem. Potentially off topic to this conversation thread, but is there anyway to just disable that check?

**Comment by dessant** [comment]
From what i understand gl 2.0 does not need to be enforced with the angle backend, please open an issue @jimanvlad if that is not the case.

**Pull request merged**
