### PR TITLE
Corrected arguments of key_up() function in keyboard example

### PR DESCRIPTION
**Pull request by CuriousLearner**
This is a fix for Issue #3853

### CODE REVIEW

**Comment by dessant** [comment]
And now we've come full circle :D.
I don't expect this to fix the original issue: https://github.com/kivy/kivy/issues/3853#issue-123087902.

**Comment by CuriousLearner** [comment]
Hi @dessant ,

I tried this patch in docked keyboard mode. I cannot re-produce the same error. Any pointers from your side would be really helpful. Thanks

**Comment by dessant** [comment]
In the issue thread you linked, it can be seen that this pr will just revert the function signature to the original state.
https://github.com/kivy/kivy/issues/3853
https://github.com/kivy/kivy/pull/3883/files

The right fix must result in all keyboard modes working with the example.

**Comment by dessant** [comment]
The pr reverts to the original state, please open a new one if you have the right fix (replacing some of the largs with keyword arguments should probably suffice).

**Pull request closed without merging**
